// Code generated by ent, DO NOT EDIT.

package joblog

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the joblog type in the database.
	Label = "job_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldTime holds the string denoting the time field in the database.
	FieldTime = "time"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldWhat holds the string denoting the what field in the database.
	FieldWhat = "what"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// EdgeJob holds the string denoting the job edge name in mutations.
	EdgeJob = "job"
	// Table holds the table name of the joblog in the database.
	Table = "job_logs"
	// JobTable is the table that holds the job relation/edge.
	JobTable = "job_logs"
	// JobInverseTable is the table name for the Job entity.
	// It exists in this package in order to avoid circular dependency with the "job" package.
	JobInverseTable = "jobs"
	// JobColumn is the table column denoting the job relation/edge.
	JobColumn = "job_logs"
)

// Columns holds all SQL columns for joblog fields.
var Columns = []string{
	FieldID,
	FieldLevel,
	FieldTime,
	FieldPath,
	FieldWhat,
	FieldSize,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "job_logs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"job_logs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTime holds the default value on creation for the "time" field.
	DefaultTime func() time.Time
)

// Level defines the type for the "level" enum field.
type Level string

// Level values.
const (
	LevelInfo    Level = "info"
	LevelWarning Level = "warning"
	LevelError   Level = "error"
)

func (l Level) String() string {
	return string(l)
}

// LevelValidator is a validator for the "level" field enum values. It is called by the builders before save.
func LevelValidator(l Level) error {
	switch l {
	case LevelInfo, LevelWarning, LevelError:
		return nil
	default:
		return fmt.Errorf("joblog: invalid enum value for level field: %q", l)
	}
}

// What defines the type for the "what" enum field.
type What string

// WhatUnknown is the default value of the What enum.
const DefaultWhat = WhatUnknown

// What values.
const (
	WhatUpload   What = "upload"
	WhatDownload What = "download"
	WhatDelete   What = "delete"
	WhatMove     What = "move"
	WhatError    What = "error"
	WhatUnknown  What = "unknown"
)

func (w What) String() string {
	return string(w)
}

// WhatValidator is a validator for the "what" field enum values. It is called by the builders before save.
func WhatValidator(w What) error {
	switch w {
	case WhatUpload, WhatDownload, WhatDelete, WhatMove, WhatError, WhatUnknown:
		return nil
	default:
		return fmt.Errorf("joblog: invalid enum value for what field: %q", w)
	}
}

// OrderOption defines the ordering options for the JobLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByTime orders the results by the time field.
func ByTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTime, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByWhat orders the results by the what field.
func ByWhat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWhat, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByJobField orders the results by job field.
func ByJobField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJobStep(), sql.OrderByField(field, opts...))
	}
}
func newJobStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JobInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, JobTable, JobColumn),
	)
}
