// Code generated by ent, DO NOT EDIT.

package joblog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/xzzpig/rclone-sync/internal/core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.JobLog {
	return predicate.JobLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.JobLog {
	return predicate.JobLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.JobLog {
	return predicate.JobLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.JobLog {
	return predicate.JobLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.JobLog {
	return predicate.JobLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.JobLog {
	return predicate.JobLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.JobLog {
	return predicate.JobLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.JobLog {
	return predicate.JobLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.JobLog {
	return predicate.JobLog(sql.FieldLTE(FieldID, id))
}

// Time applies equality check predicate on the "time" field. It's identical to TimeEQ.
func Time(v time.Time) predicate.JobLog {
	return predicate.JobLog(sql.FieldEQ(FieldTime, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.JobLog {
	return predicate.JobLog(sql.FieldEQ(FieldPath, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.JobLog {
	return predicate.JobLog(sql.FieldEQ(FieldSize, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v Level) predicate.JobLog {
	return predicate.JobLog(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v Level) predicate.JobLog {
	return predicate.JobLog(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...Level) predicate.JobLog {
	return predicate.JobLog(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...Level) predicate.JobLog {
	return predicate.JobLog(sql.FieldNotIn(FieldLevel, vs...))
}

// TimeEQ applies the EQ predicate on the "time" field.
func TimeEQ(v time.Time) predicate.JobLog {
	return predicate.JobLog(sql.FieldEQ(FieldTime, v))
}

// TimeNEQ applies the NEQ predicate on the "time" field.
func TimeNEQ(v time.Time) predicate.JobLog {
	return predicate.JobLog(sql.FieldNEQ(FieldTime, v))
}

// TimeIn applies the In predicate on the "time" field.
func TimeIn(vs ...time.Time) predicate.JobLog {
	return predicate.JobLog(sql.FieldIn(FieldTime, vs...))
}

// TimeNotIn applies the NotIn predicate on the "time" field.
func TimeNotIn(vs ...time.Time) predicate.JobLog {
	return predicate.JobLog(sql.FieldNotIn(FieldTime, vs...))
}

// TimeGT applies the GT predicate on the "time" field.
func TimeGT(v time.Time) predicate.JobLog {
	return predicate.JobLog(sql.FieldGT(FieldTime, v))
}

// TimeGTE applies the GTE predicate on the "time" field.
func TimeGTE(v time.Time) predicate.JobLog {
	return predicate.JobLog(sql.FieldGTE(FieldTime, v))
}

// TimeLT applies the LT predicate on the "time" field.
func TimeLT(v time.Time) predicate.JobLog {
	return predicate.JobLog(sql.FieldLT(FieldTime, v))
}

// TimeLTE applies the LTE predicate on the "time" field.
func TimeLTE(v time.Time) predicate.JobLog {
	return predicate.JobLog(sql.FieldLTE(FieldTime, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.JobLog {
	return predicate.JobLog(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.JobLog {
	return predicate.JobLog(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.JobLog {
	return predicate.JobLog(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.JobLog {
	return predicate.JobLog(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.JobLog {
	return predicate.JobLog(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.JobLog {
	return predicate.JobLog(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.JobLog {
	return predicate.JobLog(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.JobLog {
	return predicate.JobLog(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.JobLog {
	return predicate.JobLog(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.JobLog {
	return predicate.JobLog(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.JobLog {
	return predicate.JobLog(sql.FieldHasSuffix(FieldPath, v))
}

// PathIsNil applies the IsNil predicate on the "path" field.
func PathIsNil() predicate.JobLog {
	return predicate.JobLog(sql.FieldIsNull(FieldPath))
}

// PathNotNil applies the NotNil predicate on the "path" field.
func PathNotNil() predicate.JobLog {
	return predicate.JobLog(sql.FieldNotNull(FieldPath))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.JobLog {
	return predicate.JobLog(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.JobLog {
	return predicate.JobLog(sql.FieldContainsFold(FieldPath, v))
}

// WhatEQ applies the EQ predicate on the "what" field.
func WhatEQ(v What) predicate.JobLog {
	return predicate.JobLog(sql.FieldEQ(FieldWhat, v))
}

// WhatNEQ applies the NEQ predicate on the "what" field.
func WhatNEQ(v What) predicate.JobLog {
	return predicate.JobLog(sql.FieldNEQ(FieldWhat, v))
}

// WhatIn applies the In predicate on the "what" field.
func WhatIn(vs ...What) predicate.JobLog {
	return predicate.JobLog(sql.FieldIn(FieldWhat, vs...))
}

// WhatNotIn applies the NotIn predicate on the "what" field.
func WhatNotIn(vs ...What) predicate.JobLog {
	return predicate.JobLog(sql.FieldNotIn(FieldWhat, vs...))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.JobLog {
	return predicate.JobLog(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.JobLog {
	return predicate.JobLog(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.JobLog {
	return predicate.JobLog(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.JobLog {
	return predicate.JobLog(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.JobLog {
	return predicate.JobLog(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.JobLog {
	return predicate.JobLog(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.JobLog {
	return predicate.JobLog(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.JobLog {
	return predicate.JobLog(sql.FieldLTE(FieldSize, v))
}

// SizeIsNil applies the IsNil predicate on the "size" field.
func SizeIsNil() predicate.JobLog {
	return predicate.JobLog(sql.FieldIsNull(FieldSize))
}

// SizeNotNil applies the NotNil predicate on the "size" field.
func SizeNotNil() predicate.JobLog {
	return predicate.JobLog(sql.FieldNotNull(FieldSize))
}

// HasJob applies the HasEdge predicate on the "job" edge.
func HasJob() predicate.JobLog {
	return predicate.JobLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, JobTable, JobColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasJobWith applies the HasEdge predicate on the "job" edge with a given conditions (other predicates).
func HasJobWith(preds ...predicate.Job) predicate.JobLog {
	return predicate.JobLog(func(s *sql.Selector) {
		step := newJobStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.JobLog) predicate.JobLog {
	return predicate.JobLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.JobLog) predicate.JobLog {
	return predicate.JobLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.JobLog) predicate.JobLog {
	return predicate.JobLog(sql.NotPredicates(p))
}
