version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - dupl
    - nilerr
    - gocritic
    - gosec
    - loggercheck
    - perfsprint
    - err113

formatters:
  enable:
    - gofmt