// Code generated by ent, DO NOT EDIT.

package job

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/xzzpig/rclone-sync/internal/api/graphql/model"
	"github.com/xzzpig/rclone-sync/internal/core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldID, id))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v uuid.UUID) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldTaskID, v))
}

// StartTime applies equality check predicate on the "start_time" field. It's identical to StartTimeEQ.
func StartTime(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStartTime, v))
}

// EndTime applies equality check predicate on the "end_time" field. It's identical to EndTimeEQ.
func EndTime(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldEndTime, v))
}

// FilesTransferred applies equality check predicate on the "files_transferred" field. It's identical to FilesTransferredEQ.
func FilesTransferred(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldFilesTransferred, v))
}

// BytesTransferred applies equality check predicate on the "bytes_transferred" field. It's identical to BytesTransferredEQ.
func BytesTransferred(v int64) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldBytesTransferred, v))
}

// FilesDeleted applies equality check predicate on the "files_deleted" field. It's identical to FilesDeletedEQ.
func FilesDeleted(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldFilesDeleted, v))
}

// ErrorCount applies equality check predicate on the "error_count" field. It's identical to ErrorCountEQ.
func ErrorCount(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldErrorCount, v))
}

// Errors applies equality check predicate on the "errors" field. It's identical to ErrorsEQ.
func Errors(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldErrors, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v uuid.UUID) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v uuid.UUID) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...uuid.UUID) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...uuid.UUID) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldTaskID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v model.JobStatus) predicate.Job {
	vc := v
	return predicate.Job(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v model.JobStatus) predicate.Job {
	vc := v
	return predicate.Job(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...model.JobStatus) predicate.Job {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Job(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...model.JobStatus) predicate.Job {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Job(sql.FieldNotIn(FieldStatus, v...))
}

// TriggerEQ applies the EQ predicate on the "trigger" field.
func TriggerEQ(v model.JobTrigger) predicate.Job {
	vc := v
	return predicate.Job(sql.FieldEQ(FieldTrigger, vc))
}

// TriggerNEQ applies the NEQ predicate on the "trigger" field.
func TriggerNEQ(v model.JobTrigger) predicate.Job {
	vc := v
	return predicate.Job(sql.FieldNEQ(FieldTrigger, vc))
}

// TriggerIn applies the In predicate on the "trigger" field.
func TriggerIn(vs ...model.JobTrigger) predicate.Job {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Job(sql.FieldIn(FieldTrigger, v...))
}

// TriggerNotIn applies the NotIn predicate on the "trigger" field.
func TriggerNotIn(vs ...model.JobTrigger) predicate.Job {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Job(sql.FieldNotIn(FieldTrigger, v...))
}

// StartTimeEQ applies the EQ predicate on the "start_time" field.
func StartTimeEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStartTime, v))
}

// StartTimeNEQ applies the NEQ predicate on the "start_time" field.
func StartTimeNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldStartTime, v))
}

// StartTimeIn applies the In predicate on the "start_time" field.
func StartTimeIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldStartTime, vs...))
}

// StartTimeNotIn applies the NotIn predicate on the "start_time" field.
func StartTimeNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldStartTime, vs...))
}

// StartTimeGT applies the GT predicate on the "start_time" field.
func StartTimeGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldStartTime, v))
}

// StartTimeGTE applies the GTE predicate on the "start_time" field.
func StartTimeGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldStartTime, v))
}

// StartTimeLT applies the LT predicate on the "start_time" field.
func StartTimeLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldStartTime, v))
}

// StartTimeLTE applies the LTE predicate on the "start_time" field.
func StartTimeLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldStartTime, v))
}

// EndTimeEQ applies the EQ predicate on the "end_time" field.
func EndTimeEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldEndTime, v))
}

// EndTimeNEQ applies the NEQ predicate on the "end_time" field.
func EndTimeNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldEndTime, v))
}

// EndTimeIn applies the In predicate on the "end_time" field.
func EndTimeIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldEndTime, vs...))
}

// EndTimeNotIn applies the NotIn predicate on the "end_time" field.
func EndTimeNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldEndTime, vs...))
}

// EndTimeGT applies the GT predicate on the "end_time" field.
func EndTimeGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldEndTime, v))
}

// EndTimeGTE applies the GTE predicate on the "end_time" field.
func EndTimeGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldEndTime, v))
}

// EndTimeLT applies the LT predicate on the "end_time" field.
func EndTimeLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldEndTime, v))
}

// EndTimeLTE applies the LTE predicate on the "end_time" field.
func EndTimeLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldEndTime, v))
}

// EndTimeIsNil applies the IsNil predicate on the "end_time" field.
func EndTimeIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldEndTime))
}

// EndTimeNotNil applies the NotNil predicate on the "end_time" field.
func EndTimeNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldEndTime))
}

// FilesTransferredEQ applies the EQ predicate on the "files_transferred" field.
func FilesTransferredEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldFilesTransferred, v))
}

// FilesTransferredNEQ applies the NEQ predicate on the "files_transferred" field.
func FilesTransferredNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldFilesTransferred, v))
}

// FilesTransferredIn applies the In predicate on the "files_transferred" field.
func FilesTransferredIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldFilesTransferred, vs...))
}

// FilesTransferredNotIn applies the NotIn predicate on the "files_transferred" field.
func FilesTransferredNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldFilesTransferred, vs...))
}

// FilesTransferredGT applies the GT predicate on the "files_transferred" field.
func FilesTransferredGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldFilesTransferred, v))
}

// FilesTransferredGTE applies the GTE predicate on the "files_transferred" field.
func FilesTransferredGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldFilesTransferred, v))
}

// FilesTransferredLT applies the LT predicate on the "files_transferred" field.
func FilesTransferredLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldFilesTransferred, v))
}

// FilesTransferredLTE applies the LTE predicate on the "files_transferred" field.
func FilesTransferredLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldFilesTransferred, v))
}

// BytesTransferredEQ applies the EQ predicate on the "bytes_transferred" field.
func BytesTransferredEQ(v int64) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldBytesTransferred, v))
}

// BytesTransferredNEQ applies the NEQ predicate on the "bytes_transferred" field.
func BytesTransferredNEQ(v int64) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldBytesTransferred, v))
}

// BytesTransferredIn applies the In predicate on the "bytes_transferred" field.
func BytesTransferredIn(vs ...int64) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldBytesTransferred, vs...))
}

// BytesTransferredNotIn applies the NotIn predicate on the "bytes_transferred" field.
func BytesTransferredNotIn(vs ...int64) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldBytesTransferred, vs...))
}

// BytesTransferredGT applies the GT predicate on the "bytes_transferred" field.
func BytesTransferredGT(v int64) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldBytesTransferred, v))
}

// BytesTransferredGTE applies the GTE predicate on the "bytes_transferred" field.
func BytesTransferredGTE(v int64) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldBytesTransferred, v))
}

// BytesTransferredLT applies the LT predicate on the "bytes_transferred" field.
func BytesTransferredLT(v int64) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldBytesTransferred, v))
}

// BytesTransferredLTE applies the LTE predicate on the "bytes_transferred" field.
func BytesTransferredLTE(v int64) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldBytesTransferred, v))
}

// FilesDeletedEQ applies the EQ predicate on the "files_deleted" field.
func FilesDeletedEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldFilesDeleted, v))
}

// FilesDeletedNEQ applies the NEQ predicate on the "files_deleted" field.
func FilesDeletedNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldFilesDeleted, v))
}

// FilesDeletedIn applies the In predicate on the "files_deleted" field.
func FilesDeletedIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldFilesDeleted, vs...))
}

// FilesDeletedNotIn applies the NotIn predicate on the "files_deleted" field.
func FilesDeletedNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldFilesDeleted, vs...))
}

// FilesDeletedGT applies the GT predicate on the "files_deleted" field.
func FilesDeletedGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldFilesDeleted, v))
}

// FilesDeletedGTE applies the GTE predicate on the "files_deleted" field.
func FilesDeletedGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldFilesDeleted, v))
}

// FilesDeletedLT applies the LT predicate on the "files_deleted" field.
func FilesDeletedLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldFilesDeleted, v))
}

// FilesDeletedLTE applies the LTE predicate on the "files_deleted" field.
func FilesDeletedLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldFilesDeleted, v))
}

// ErrorCountEQ applies the EQ predicate on the "error_count" field.
func ErrorCountEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldErrorCount, v))
}

// ErrorCountNEQ applies the NEQ predicate on the "error_count" field.
func ErrorCountNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldErrorCount, v))
}

// ErrorCountIn applies the In predicate on the "error_count" field.
func ErrorCountIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldErrorCount, vs...))
}

// ErrorCountNotIn applies the NotIn predicate on the "error_count" field.
func ErrorCountNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldErrorCount, vs...))
}

// ErrorCountGT applies the GT predicate on the "error_count" field.
func ErrorCountGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldErrorCount, v))
}

// ErrorCountGTE applies the GTE predicate on the "error_count" field.
func ErrorCountGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldErrorCount, v))
}

// ErrorCountLT applies the LT predicate on the "error_count" field.
func ErrorCountLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldErrorCount, v))
}

// ErrorCountLTE applies the LTE predicate on the "error_count" field.
func ErrorCountLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldErrorCount, v))
}

// ErrorsEQ applies the EQ predicate on the "errors" field.
func ErrorsEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldErrors, v))
}

// ErrorsNEQ applies the NEQ predicate on the "errors" field.
func ErrorsNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldErrors, v))
}

// ErrorsIn applies the In predicate on the "errors" field.
func ErrorsIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldErrors, vs...))
}

// ErrorsNotIn applies the NotIn predicate on the "errors" field.
func ErrorsNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldErrors, vs...))
}

// ErrorsGT applies the GT predicate on the "errors" field.
func ErrorsGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldErrors, v))
}

// ErrorsGTE applies the GTE predicate on the "errors" field.
func ErrorsGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldErrors, v))
}

// ErrorsLT applies the LT predicate on the "errors" field.
func ErrorsLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldErrors, v))
}

// ErrorsLTE applies the LTE predicate on the "errors" field.
func ErrorsLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldErrors, v))
}

// ErrorsContains applies the Contains predicate on the "errors" field.
func ErrorsContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldErrors, v))
}

// ErrorsHasPrefix applies the HasPrefix predicate on the "errors" field.
func ErrorsHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldErrors, v))
}

// ErrorsHasSuffix applies the HasSuffix predicate on the "errors" field.
func ErrorsHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldErrors, v))
}

// ErrorsIsNil applies the IsNil predicate on the "errors" field.
func ErrorsIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldErrors))
}

// ErrorsNotNil applies the NotNil predicate on the "errors" field.
func ErrorsNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldErrors))
}

// ErrorsEqualFold applies the EqualFold predicate on the "errors" field.
func ErrorsEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldErrors, v))
}

// ErrorsContainsFold applies the ContainsFold predicate on the "errors" field.
func ErrorsContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldErrors, v))
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLogs applies the HasEdge predicate on the "logs" edge.
func HasLogs() predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LogsTable, LogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLogsWith applies the HasEdge predicate on the "logs" edge with a given conditions (other predicates).
func HasLogsWith(preds ...predicate.JobLog) predicate.Job {
	return predicate.Job(func(s *sql.Selector) {
		step := newLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Job) predicate.Job {
	return predicate.Job(sql.NotPredicates(p))
}
