// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/xzzpig/rclone-sync/internal/core/ent/runtime.go

const (
	Version = "0.14.3"                                              // Version of ent codegen.
	Sum     = "sha256-rKGzYOdNaSbFyHIuytuppYjpiTz1/tcvXel1SjtwEhA=" // Sum of ent codegen.
)
