/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'BigInt': unknown;
    'Boolean': unknown;
    'ConflictResolution': { name: 'ConflictResolution'; enumValues: 'NEWER' | 'LOCAL' | 'REMOTE' | 'BOTH'; };
    'Connection': { kind: 'OBJECT'; name: 'Connection'; fields: { 'config': { name: 'config'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'StringMap'; ofType: null; }; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'loadError': { name: 'loadError'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'loadStatus': { name: 'loadStatus'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'ConnectionLoadStatus'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'quota': { name: 'quota'; type: { kind: 'OBJECT'; name: 'ConnectionQuota'; ofType: null; } }; 'tasks': { name: 'tasks'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TaskConnection'; ofType: null; }; } }; 'type': { name: 'type'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; }; };
    'ConnectionConnection': { kind: 'OBJECT'; name: 'ConnectionConnection'; fields: { 'items': { name: 'items'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Connection'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'OffsetPageInfo'; ofType: null; }; } }; 'totalCount': { name: 'totalCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'ConnectionLoadStatus': { name: 'ConnectionLoadStatus'; enumValues: 'LOADED' | 'LOADING' | 'ERROR'; };
    'ConnectionMutation': { kind: 'OBJECT'; name: 'ConnectionMutation'; fields: { 'create': { name: 'create'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Connection'; ofType: null; }; } }; 'delete': { name: 'delete'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Connection'; ofType: null; }; } }; 'test': { name: 'test'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'TestConnectionResult'; ofType: null; }; } }; 'testUnsaved': { name: 'testUnsaved'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'TestConnectionResult'; ofType: null; }; } }; 'update': { name: 'update'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Connection'; ofType: null; }; } }; }; };
    'ConnectionQuery': { kind: 'OBJECT'; name: 'ConnectionQuery'; fields: { 'get': { name: 'get'; type: { kind: 'OBJECT'; name: 'Connection'; ofType: null; } }; 'list': { name: 'list'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ConnectionConnection'; ofType: null; }; } }; }; };
    'ConnectionQuota': { kind: 'OBJECT'; name: 'ConnectionQuota'; fields: { 'free': { name: 'free'; type: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; } }; 'objects': { name: 'objects'; type: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; } }; 'other': { name: 'other'; type: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; } }; 'total': { name: 'total'; type: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; } }; 'trashed': { name: 'trashed'; type: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; } }; 'used': { name: 'used'; type: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; } }; }; };
    'ConnectionTestFailure': { kind: 'OBJECT'; name: 'ConnectionTestFailure'; fields: { 'error': { name: 'error'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'ConnectionTestSuccess': { kind: 'OBJECT'; name: 'ConnectionTestSuccess'; fields: { 'message': { name: 'message'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'CreateConnectionInput': { kind: 'INPUT_OBJECT'; name: 'CreateConnectionInput'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'type'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'config'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'StringMap'; ofType: null; }; }; defaultValue: null }]; };
    'CreateTaskInput': { kind: 'INPUT_OBJECT'; name: 'CreateTaskInput'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'sourcePath'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'connectionId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'remotePath'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'direction'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'SyncDirection'; ofType: null; }; }; defaultValue: null }, { name: 'schedule'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'realtime'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: "false" }, { name: 'options'; type: { kind: 'INPUT_OBJECT'; name: 'TaskSyncOptionsInput'; ofType: null; }; defaultValue: null }]; };
    'DateTime': unknown;
    'FileEntry': { kind: 'OBJECT'; name: 'FileEntry'; fields: { 'isDir': { name: 'isDir'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'FileQuery': { kind: 'OBJECT'; name: 'FileQuery'; fields: { 'list': { name: 'list'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'FileEntry'; ofType: null; }; }; }; } }; }; };
    'ID': unknown;
    'ImportConnectionInput': { kind: 'INPUT_OBJECT'; name: 'ImportConnectionInput'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'type'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'config'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'StringMap'; ofType: null; }; }; defaultValue: null }]; };
    'ImportExecuteInput': { kind: 'INPUT_OBJECT'; name: 'ImportExecuteInput'; isOneOf: false; inputFields: [{ name: 'connections'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'ImportConnectionInput'; ofType: null; }; }; }; }; defaultValue: null }]; };
    'ImportExecuteResult': { kind: 'OBJECT'; name: 'ImportExecuteResult'; fields: { 'connections': { name: 'connections'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Connection'; ofType: null; }; }; }; } }; 'skippedCount': { name: 'skippedCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'ImportMutation': { kind: 'OBJECT'; name: 'ImportMutation'; fields: { 'execute': { name: 'execute'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ImportExecuteResult'; ofType: null; }; } }; 'parse': { name: 'parse'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'UNION'; name: 'ImportParseResult'; ofType: null; }; } }; }; };
    'ImportParseError': { kind: 'OBJECT'; name: 'ImportParseError'; fields: { 'error': { name: 'error'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'line': { name: 'line'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'ImportParseInput': { kind: 'INPUT_OBJECT'; name: 'ImportParseInput'; isOneOf: false; inputFields: [{ name: 'content'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'ImportParseResult': { kind: 'UNION'; name: 'ImportParseResult'; fields: {}; possibleTypes: 'ImportParseError' | 'ImportParseSuccess'; };
    'ImportParseSuccess': { kind: 'OBJECT'; name: 'ImportParseSuccess'; fields: { 'connections': { name: 'connections'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ParsedConnection'; ofType: null; }; }; }; } }; }; };
    'Int': unknown;
    'JSON': unknown;
    'Job': { kind: 'OBJECT'; name: 'Job'; fields: { 'bytesTransferred': { name: 'bytesTransferred'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; 'endTime': { name: 'endTime'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'errorCount': { name: 'errorCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'errors': { name: 'errors'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'filesDeleted': { name: 'filesDeleted'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'filesTransferred': { name: 'filesTransferred'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'logs': { name: 'logs'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'JobLogConnection'; ofType: null; }; } }; 'progress': { name: 'progress'; type: { kind: 'OBJECT'; name: 'JobProgressEvent'; ofType: null; } }; 'startTime': { name: 'startTime'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'JobStatus'; ofType: null; }; } }; 'task': { name: 'task'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Task'; ofType: null; }; } }; 'trigger': { name: 'trigger'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'JobTrigger'; ofType: null; }; } }; }; };
    'JobConnection': { kind: 'OBJECT'; name: 'JobConnection'; fields: { 'items': { name: 'items'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Job'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'OffsetPageInfo'; ofType: null; }; } }; 'totalCount': { name: 'totalCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'JobLog': { kind: 'OBJECT'; name: 'JobLog'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'job': { name: 'job'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Job'; ofType: null; }; } }; 'level': { name: 'level'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'LogLevel'; ofType: null; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'size': { name: 'size'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; 'time': { name: 'time'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'what': { name: 'what'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'LogAction'; ofType: null; }; } }; }; };
    'JobLogConnection': { kind: 'OBJECT'; name: 'JobLogConnection'; fields: { 'items': { name: 'items'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'JobLog'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'OffsetPageInfo'; ofType: null; }; } }; 'totalCount': { name: 'totalCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'JobProgressEvent': { kind: 'OBJECT'; name: 'JobProgressEvent'; fields: { 'bytesTotal': { name: 'bytesTotal'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; 'bytesTransferred': { name: 'bytesTransferred'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; 'connectionId': { name: 'connectionId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'endTime': { name: 'endTime'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'errorCount': { name: 'errorCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'filesDeleted': { name: 'filesDeleted'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'filesTotal': { name: 'filesTotal'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'filesTransferred': { name: 'filesTransferred'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'jobId': { name: 'jobId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'startTime': { name: 'startTime'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'JobStatus'; ofType: null; }; } }; 'taskId': { name: 'taskId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'JobQuery': { kind: 'OBJECT'; name: 'JobQuery'; fields: { 'get': { name: 'get'; type: { kind: 'OBJECT'; name: 'Job'; ofType: null; } }; 'list': { name: 'list'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'JobConnection'; ofType: null; }; } }; 'progress': { name: 'progress'; type: { kind: 'OBJECT'; name: 'JobProgressEvent'; ofType: null; } }; }; };
    'JobStatus': { name: 'JobStatus'; enumValues: 'PENDING' | 'RUNNING' | 'SUCCESS' | 'FAILED' | 'CANCELLED'; };
    'JobTrigger': { name: 'JobTrigger'; enumValues: 'MANUAL' | 'SCHEDULE' | 'REALTIME'; };
    'LogAction': { name: 'LogAction'; enumValues: 'UPLOAD' | 'DOWNLOAD' | 'DELETE' | 'MOVE' | 'ERROR' | 'UNKNOWN'; };
    'LogLevel': { name: 'LogLevel'; enumValues: 'INFO' | 'WARNING' | 'ERROR'; };
    'LogQuery': { kind: 'OBJECT'; name: 'LogQuery'; fields: { 'list': { name: 'list'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'JobLogConnection'; ofType: null; }; } }; }; };
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'connection': { name: 'connection'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ConnectionMutation'; ofType: null; }; } }; 'import': { name: 'import'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ImportMutation'; ofType: null; }; } }; 'task': { name: 'task'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TaskMutation'; ofType: null; }; } }; }; };
    'OffsetPageInfo': { kind: 'OBJECT'; name: 'OffsetPageInfo'; fields: { 'hasNextPage': { name: 'hasNextPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'hasPreviousPage': { name: 'hasPreviousPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'limit': { name: 'limit'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'offset': { name: 'offset'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'OptionExample': { kind: 'OBJECT'; name: 'OptionExample'; fields: { 'help': { name: 'help'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'value': { name: 'value'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'PaginationInput': { kind: 'INPUT_OBJECT'; name: 'PaginationInput'; isOneOf: false; inputFields: [{ name: 'limit'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: "20" }, { name: 'offset'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: "0" }]; };
    'ParsedConnection': { kind: 'OBJECT'; name: 'ParsedConnection'; fields: { 'config': { name: 'config'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'StringMap'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'type': { name: 'type'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Provider': { kind: 'OBJECT'; name: 'Provider'; fields: { 'description': { name: 'description'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'options': { name: 'options'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ProviderOption'; ofType: null; }; }; }; } }; 'prefix': { name: 'prefix'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'ProviderOption': { kind: 'OBJECT'; name: 'ProviderOption'; fields: { 'advanced': { name: 'advanced'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'default': { name: 'default'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'examples': { name: 'examples'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'OptionExample'; ofType: null; }; }; } }; 'exclusive': { name: 'exclusive'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'groups': { name: 'groups'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'help': { name: 'help'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'isPassword': { name: 'isPassword'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'required': { name: 'required'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'type': { name: 'type'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'ProviderQuery': { kind: 'OBJECT'; name: 'ProviderQuery'; fields: { 'get': { name: 'get'; type: { kind: 'OBJECT'; name: 'Provider'; ofType: null; } }; 'list': { name: 'list'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Provider'; ofType: null; }; }; }; } }; }; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'connection': { name: 'connection'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ConnectionQuery'; ofType: null; }; } }; 'file': { name: 'file'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'FileQuery'; ofType: null; }; } }; 'job': { name: 'job'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'JobQuery'; ofType: null; }; } }; 'log': { name: 'log'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'LogQuery'; ofType: null; }; } }; 'provider': { name: 'provider'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ProviderQuery'; ofType: null; }; } }; 'task': { name: 'task'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TaskQuery'; ofType: null; }; } }; }; };
    'String': unknown;
    'StringMap': unknown;
    'Subscription': { kind: 'OBJECT'; name: 'Subscription'; fields: { 'jobProgress': { name: 'jobProgress'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'JobProgressEvent'; ofType: null; }; } }; 'transferProgress': { name: 'transferProgress'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TransferProgressEvent'; ofType: null; }; } }; }; };
    'SyncDirection': { name: 'SyncDirection'; enumValues: 'UPLOAD' | 'DOWNLOAD' | 'BIDIRECTIONAL'; };
    'Task': { kind: 'OBJECT'; name: 'Task'; fields: { 'connection': { name: 'connection'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Connection'; ofType: null; }; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'direction': { name: 'direction'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'SyncDirection'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'jobs': { name: 'jobs'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'JobConnection'; ofType: null; }; } }; 'latestJob': { name: 'latestJob'; type: { kind: 'OBJECT'; name: 'Job'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'options': { name: 'options'; type: { kind: 'OBJECT'; name: 'TaskSyncOptions'; ofType: null; } }; 'realtime': { name: 'realtime'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'remotePath': { name: 'remotePath'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'schedule': { name: 'schedule'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'sourcePath': { name: 'sourcePath'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; }; };
    'TaskConnection': { kind: 'OBJECT'; name: 'TaskConnection'; fields: { 'items': { name: 'items'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Task'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'OffsetPageInfo'; ofType: null; }; } }; 'totalCount': { name: 'totalCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'TaskMutation': { kind: 'OBJECT'; name: 'TaskMutation'; fields: { 'create': { name: 'create'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Task'; ofType: null; }; } }; 'delete': { name: 'delete'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Task'; ofType: null; }; } }; 'run': { name: 'run'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Job'; ofType: null; }; } }; 'update': { name: 'update'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Task'; ofType: null; }; } }; }; };
    'TaskQuery': { kind: 'OBJECT'; name: 'TaskQuery'; fields: { 'get': { name: 'get'; type: { kind: 'OBJECT'; name: 'Task'; ofType: null; } }; 'list': { name: 'list'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TaskConnection'; ofType: null; }; } }; }; };
    'TaskSyncOptions': { kind: 'OBJECT'; name: 'TaskSyncOptions'; fields: { 'conflictResolution': { name: 'conflictResolution'; type: { kind: 'ENUM'; name: 'ConflictResolution'; ofType: null; } }; 'filters': { name: 'filters'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; } }; 'noDelete': { name: 'noDelete'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; } }; 'transfers': { name: 'transfers'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; }; };
    'TaskSyncOptionsInput': { kind: 'INPUT_OBJECT'; name: 'TaskSyncOptionsInput'; isOneOf: false; inputFields: [{ name: 'conflictResolution'; type: { kind: 'ENUM'; name: 'ConflictResolution'; ofType: null; }; defaultValue: null }, { name: 'filters'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; defaultValue: null }, { name: 'noDelete'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: 'transfers'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }]; };
    'TestConnectionInput': { kind: 'INPUT_OBJECT'; name: 'TestConnectionInput'; isOneOf: false; inputFields: [{ name: 'type'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'config'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'StringMap'; ofType: null; }; }; defaultValue: null }]; };
    'TestConnectionResult': { kind: 'UNION'; name: 'TestConnectionResult'; fields: {}; possibleTypes: 'ConnectionTestFailure' | 'ConnectionTestSuccess'; };
    'TransferItem': { kind: 'OBJECT'; name: 'TransferItem'; fields: { 'bytes': { name: 'bytes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'size': { name: 'size'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'BigInt'; ofType: null; }; } }; }; };
    'TransferProgressEvent': { kind: 'OBJECT'; name: 'TransferProgressEvent'; fields: { 'connectionId': { name: 'connectionId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'jobId': { name: 'jobId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'taskId': { name: 'taskId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'transfers': { name: 'transfers'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TransferItem'; ofType: null; }; }; }; } }; }; };
    'UpdateConnectionInput': { kind: 'INPUT_OBJECT'; name: 'UpdateConnectionInput'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'config'; type: { kind: 'SCALAR'; name: 'StringMap'; ofType: null; }; defaultValue: null }]; };
    'UpdateTaskInput': { kind: 'INPUT_OBJECT'; name: 'UpdateTaskInput'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'sourcePath'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'connectionId'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }, { name: 'remotePath'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'direction'; type: { kind: 'ENUM'; name: 'SyncDirection'; ofType: null; }; defaultValue: null }, { name: 'schedule'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'realtime'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: 'options'; type: { kind: 'INPUT_OBJECT'; name: 'TaskSyncOptionsInput'; ofType: null; }; defaultValue: null }]; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: 'Subscription';
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}