// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

// 导入解析结果
type ImportParseResult interface {
	IsImportParseResult()
}

// 测试连接结果
type TestConnectionResult interface {
	IsTestConnectionResult()
}

// 应用全局配置
type AppConfig struct {
	// Hook 相关配置
	Hook *AppHookConfig `json:"hook"`
}

// Hook 全局配置
type AppHookConfig struct {
	// 是否全局启用 Hook 功能
	Enabled bool `json:"enabled"`
}

// 清理缓存结果
type ClearCacheResult struct {
	// 是否成功
	Success bool `json:"success"`
	// 清理的条目数量
	ClearedCount int `json:"clearedCount"`
	// 消息（已本地化）
	Message string `json:"message"`
}

// 远程存储连接
type Connection struct {
	// UUID 主键
	ID uuid.UUID `json:"id"`
	// 连接名称（系统唯一）
	Name string `json:"name"`
	// 提供者类型（如 onedrive, s3, drive）
	Type string `json:"type"`
	// 配置参数（解密后，需要解密处理）
	Config map[string]string `json:"config"`
	// 加载状态（运行时状态）
	LoadStatus ConnectionLoadStatus `json:"loadStatus"`
	// 加载错误信息（运行时状态，仅当 loadStatus 为 ERROR 时有值）
	LoadError *string `json:"loadError,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"createdAt"`
	// 更新时间
	UpdatedAt time.Time `json:"updatedAt"`
	// 使用此连接的任务（分页查询）
	Tasks *TaskConnection `json:"tasks"`
	// 配额信息（调用 rclone about API）
	Quota *ConnectionQuota `json:"quota,omitempty"`
	// 连接扩展选项（包含缓存配置）
	Options *ConnectionOptions `json:"options,omitempty"`
	// 缓存运行时状态（仅当 options.cache.enabled 为 true 时有值）
	// 这是一个计算字段，不持久化
	CacheStatus *ConnectionCacheStatus `json:"cacheStatus,omitempty"`
	// 关联的 Hooks 列表（作为共享 Hooks，关联任务触发事件时会被执行）
	Hooks []*Hook `json:"hooks"`
}

// 元数据缓存配置（持久化配置）
type ConnectionCacheOptions struct {
	// 是否启用元数据缓存
	Enabled bool `json:"enabled"`
	// 缓存过期时间（Go duration 格式，如 "6h", "24h"）
	// 空值表示使用默认值（6小时）
	// "0" 或负值表示永不过期（不推荐）
	InfoAge *string `json:"infoAge,omitempty"`
	// ChangeNotify 轮询间隔（Go duration 格式，如 "1m", "5m"）
	// 空值表示使用默认值（1分钟）
	// 最小值为 10s
	ChangeNotifyPoll *string `json:"changeNotifyPoll,omitempty"`
}

// 元数据缓存配置输入
type ConnectionCacheOptionsInput struct {
	// 是否启用元数据缓存
	Enabled bool `json:"enabled"`
	// 缓存过期时间（Go duration 格式，如 "6h", "24h"）
	// 空值或空字符串表示使用默认值（6小时）
	InfoAge *string `json:"infoAge,omitempty"`
	// ChangeNotify 轮询间隔（Go duration 格式，如 "1m", "5m"）
	// 空值或空字符串表示使用默认值（1分钟）
	ChangeNotifyPoll *string `json:"changeNotifyPoll,omitempty"`
}

// 元数据缓存运行时状态（计算字段）
type ConnectionCacheStatus struct {
	// 连接 ID
	ConnectionID uuid.UUID `json:"connectionId"`
	// 缓存是否正在运行（Fs 已 Pin 且 ChangeNotify 已订阅）
	Running bool `json:"running"`
	// ChangeNotify 是否可用（后端是否支持）
	ChangeNotifySupported bool `json:"changeNotifySupported"`
	// 缓存条目数量
	EntriesCount int `json:"entriesCount"`
	// 缓存数据库文件大小（字节）
	DbSizeBytes *int64 `json:"dbSizeBytes,omitempty"`
	// 最后一次收到变更通知的时间（用于监控）
	LastNotifyTime *time.Time `json:"lastNotifyTime,omitempty"`
}

// 连接分页连接
type ConnectionConnection struct {
	// 连接列表
	Items []*Connection `json:"items"`
	// 总数
	TotalCount int `json:"totalCount"`
	// 分页信息
	PageInfo *OffsetPageInfo `json:"pageInfo"`
}

// 连接变更命名空间
type ConnectionMutation struct {
	// 创建连接（失败抛出 GraphQL error）
	Create *Connection `json:"create"`
	// 更新连接（失败抛出 GraphQL error）
	Update *Connection `json:"update"`
	// 删除连接（失败抛出 GraphQL error）
	Delete *Connection `json:"delete"`
	// 测试已保存的连接（测试失败是预期业务结果，用 union 表示）
	Test TestConnectionResult `json:"test"`
	// 测试未保存的连接配置（测试失败是预期业务结果，用 union 表示）
	TestUnsaved TestConnectionResult `json:"testUnsaved"`
	// 清理指定连接的缓存数据
	// - id: 连接 ID
	// 返回清理结果
	ClearCache *ClearCacheResult `json:"clearCache"`
}

// 连接扩展选项
type ConnectionOptions struct {
	// 元数据缓存配置
	Cache *ConnectionCacheOptions `json:"cache,omitempty"`
}

// 连接扩展选项输入
type ConnectionOptionsInput struct {
	// 元数据缓存配置
	Cache *ConnectionCacheOptionsInput `json:"cache,omitempty"`
}

// 连接查询命名空间
type ConnectionQuery struct {
	// 获取连接列表
	List *ConnectionConnection `json:"list"`
	// 获取单个连接
	Get *Connection `json:"get,omitempty"`
}

// 连接配额信息
type ConnectionQuota struct {
	// 总空间（字节），可能为 null 如果存储不支持
	Total *int64 `json:"total,omitempty"`
	// 已使用空间（字节），可能为 null 如果存储不支持
	Used *int64 `json:"used,omitempty"`
	// 可用空间（字节），可能为 null 如果存储不支持
	Free *int64 `json:"free,omitempty"`
	// 回收站占用空间（字节），可能为 null 如果存储不支持
	Trashed *int64 `json:"trashed,omitempty"`
	// 其他空间占用（字节），如版本控制、元数据等，可能为 null
	Other *int64 `json:"other,omitempty"`
	// 对象/文件数量，可能为 null 如果存储不支持
	Objects *int64 `json:"objects,omitempty"`
}

// 连接测试失败
type ConnectionTestFailure struct {
	// 错误消息（已本地化）
	Error string `json:"error"`
}

func (ConnectionTestFailure) IsTestConnectionResult() {}

// 连接测试成功
type ConnectionTestSuccess struct {
	// 成功消息（已本地化）
	Message string `json:"message"`
}

func (ConnectionTestSuccess) IsTestConnectionResult() {}

// 创建连接输入
type CreateConnectionInput struct {
	// 连接名称
	Name string `json:"name"`
	// 提供者类型
	Type string `json:"type"`
	// 配置参数
	Config map[string]string `json:"config"`
	// 连接扩展选项（包含缓存配置）
	Options *ConnectionOptionsInput `json:"options,omitempty"`
}

// 创建任务输入
type CreateTaskInput struct {
	// 任务名称
	Name string `json:"name"`
	// 本地源路径
	SourcePath string `json:"sourcePath"`
	// 关联连接 ID
	ConnectionID uuid.UUID `json:"connectionId"`
	// 远程目标路径
	RemotePath string `json:"remotePath"`
	// 同步方向
	Direction SyncDirection `json:"direction"`
	// Cron 调度表达式
	Schedule *string `json:"schedule,omitempty"`
	// 是否启用实时同步
	Realtime *bool `json:"realtime,omitempty"`
	// 任务是否启用
	Enabled *bool `json:"enabled,omitempty"`
	// 同步选项
	Options *TaskSyncOptionsInput `json:"options,omitempty"`
	// 关联的 Hooks
	Hooks []*HookInput `json:"hooks,omitempty"`
}

// 文件/目录条目
type FileEntry struct {
	// 文件名
	Name string `json:"name"`
	// 完整路径
	Path string `json:"path"`
	// 是否为目录
	IsDir bool `json:"isDir"`
}

// 文件查询命名空间
type FileQuery struct {
	// 列出目录内容（统一接口，支持本地和远程）
	// 当 connectionId 为空时访问本地路径，否则访问远程连接
	// 支持过滤器预览功能
	List []*FileEntry `json:"list"`
}

// Hook 配置
type Hook struct {
	// UUID 主键
	ID uuid.UUID `json:"id"`
	// 是否启用
	Enabled bool `json:"enabled"`
	// 执行优先级（升序，null 排最后）
	Priority *int `json:"priority,omitempty"`
	// 触发事件类型
	Event HookEvent `json:"event"`
	// Hook 类型
	Type HookType `json:"type"`
	// 错误处理行为
	OnError HookOnError `json:"onError"`
	// Hook 配置（强类型结构体）
	Config *HookConfig `json:"config"`
	// 关联的任务（与 connection 互斥）
	Task *Task `json:"task,omitempty"`
	// 关联的连接（与 task 互斥）
	Connection *Connection `json:"connection,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"createdAt"`
	// 更新时间
	UpdatedAt    time.Time  `json:"updatedAt"`
	ConnectionID *uuid.UUID `json:"-"`
	TaskID       *uuid.UUID `json:"-"`
}

// Hook 配置（统一结构体，根据 Hook.type 使用不同字段子集）
type HookConfig struct {
	// 请求 URL（支持 Go text/template 语法）- HTTP Hook
	URL *string `json:"url,omitempty"`
	// HTTP 方法（GET/POST/PUT），默认 POST - HTTP Hook
	Method *string `json:"method,omitempty"`
	// 自定义请求头 - HTTP Hook
	Headers map[string]string `json:"headers,omitempty"`
	// 请求体模板（支持 Go text/template 语法）- HTTP Hook
	Body *string `json:"body,omitempty"`
	// Shell 命令（支持 Go text/template 语法）- Command Hook
	Command *string `json:"command,omitempty"`
	// 工作目录 - Command Hook
	WorkDir *string `json:"workDir,omitempty"`
	// 执行超时时间（秒），默认 30 - Command Hook
	Timeout *int `json:"timeout,omitempty"`
}

// Hook 配置输入（统一结构体，根据 Hook.type 填写对应字段）
type HookConfigInput struct {
	// 请求 URL（支持 Go text/template 语法）- HTTP Hook 必填
	URL *string `json:"url,omitempty"`
	// HTTP 方法（GET/POST/PUT），默认 POST - HTTP Hook
	Method *string `json:"method,omitempty"`
	// 自定义请求头 - HTTP Hook
	Headers map[string]string `json:"headers,omitempty"`
	// 请求体模板（支持 Go text/template 语法）- HTTP Hook
	Body *string `json:"body,omitempty"`
	// Shell 命令（支持 Go text/template 语法）- Command Hook 必填
	Command *string `json:"command,omitempty"`
	// 工作目录 - Command Hook
	WorkDir *string `json:"workDir,omitempty"`
	// 执行超时时间（秒），默认 30 - Command Hook
	Timeout *int `json:"timeout,omitempty"`
}

// Hook 的核心配置字段
type HookInput struct {
	// 是否启用，默认 true
	Enabled *bool `json:"enabled,omitempty"`
	// 执行优先级（升序，null 排最后）
	Priority *int `json:"priority,omitempty"`
	// 触发事件类型
	Event HookEvent `json:"event"`
	// Hook 类型
	Type HookType `json:"type"`
	// 错误处理行为，默认 IGNORE
	OnError *HookOnError `json:"onError,omitempty"`
	// Hook 配置数据
	Config *HookConfigInput `json:"config"`
}

// Hook 变更命名空间
type HookMutation struct {
	// 创建 Hook。taskId 和 connectionId 作为内联参数（二选一），配置数据通过 input 传递。
	Create *Hook `json:"create"`
	// 更新 Hook（失败抛出 GraphQL error）
	Update *Hook `json:"update"`
	// 删除 Hook（失败抛出 GraphQL error）
	Delete *Hook `json:"delete"`
}

// Hook 查询命名空间
type HookQuery struct {
	// 获取 Hook 列表
	// - taskId: 按任务 ID 过滤
	// - connectionId: 按连接 ID 过滤
	// - event: 按事件类型过滤
	// 至少需要提供 taskId 或 connectionId 之一
	List []*Hook `json:"list"`
	// 获取单个 Hook
	Get *Hook `json:"get,omitempty"`
}

// 导入连接输入
type ImportConnectionInput struct {
	// 连接名称
	Name string `json:"name"`
	// 提供者类型
	Type string `json:"type"`
	// 配置参数
	Config map[string]string `json:"config"`
}

// 导入执行输入
type ImportExecuteInput struct {
	// 要导入的连接列表
	Connections []*ImportConnectionInput `json:"connections"`
	// 是否覆盖已存在的连接（默认为 true）
	Overwrite bool `json:"overwrite"`
}

// 导入执行结果
type ImportExecuteResult struct {
	// 成功导入的连接列表（包含新创建和更新的连接）
	Connections []*Connection `json:"connections"`
	// 新创建的连接数
	CreatedCount int `json:"createdCount"`
	// 更新的连接数
	UpdatedCount int `json:"updatedCount"`
}

// 导入变更命名空间
type ImportMutation struct {
	// 解析 rclone 配置文件（解析失败是预期业务结果，用 union 表示）
	Parse ImportParseResult `json:"parse"`
	// 执行导入（失败抛出 GraphQL error）
	Execute *ImportExecuteResult `json:"execute"`
}

// 导入解析错误
type ImportParseError struct {
	// 错误消息（已本地化）
	Error string `json:"error"`
	// 错误行号
	Line *int `json:"line,omitempty"`
}

func (ImportParseError) IsImportParseResult() {}

// 导入解析输入
type ImportParseInput struct {
	// rclone 配置文件内容
	Content string `json:"content"`
}

// 导入解析成功
type ImportParseSuccess struct {
	// 解析出的连接列表
	Connections []*ParsedConnection `json:"connections"`
}

func (ImportParseSuccess) IsImportParseResult() {}

// 作业执行记录
type Job struct {
	// UUID 主键
	ID uuid.UUID `json:"id"`
	// 执行状态
	Status JobStatus `json:"status"`
	// 触发方式
	Trigger JobTrigger `json:"trigger"`
	// 开始时间
	StartTime time.Time `json:"startTime"`
	// 结束时间
	EndTime *time.Time `json:"endTime,omitempty"`
	// 已传输文件数
	FilesTransferred int `json:"filesTransferred"`
	// 已传输字节数
	BytesTransferred int64 `json:"bytesTransferred"`
	// 删除的文件数
	FilesDeleted int `json:"filesDeleted"`
	// 错误数量
	ErrorCount int `json:"errorCount"`
	// 错误信息
	Errors *string `json:"errors,omitempty"`
	// 关联的任务（ent edge）
	Task *Task `json:"task"`
	// 执行日志（分页查询）
	Logs *JobLogConnection `json:"logs"`
	// 运行时进度（仅 RUNNING 状态的 job 有值，其他状态返回 null）
	Progress *JobProgressEvent `json:"progress,omitempty"`
	TaskID   uuid.UUID         `json:"-"`
}

// 作业分页连接
type JobConnection struct {
	// 作业列表
	Items []*Job `json:"items"`
	// 总数
	TotalCount int `json:"totalCount"`
	// 分页信息
	PageInfo *OffsetPageInfo `json:"pageInfo"`
}

// 作业日志条目
type JobLog struct {
	// 自增主键
	ID int `json:"id"`
	// 日志级别
	Level LogLevel `json:"level"`
	// 日志时间
	Time time.Time `json:"time"`
	// 文件路径
	Path string `json:"path"`
	// 操作类型
	What LogAction `json:"what"`
	// 文件大小（字节）
	// 注意：当 what = HOOK 时，此字段表示 hook 执行耗时（毫秒）
	Size int64 `json:"size"`
	// 关联的作业（ent edge）
	Job   *Job      `json:"job"`
	JobID uuid.UUID `json:"-"`
}

// 日志分页连接
type JobLogConnection struct {
	// 日志列表
	Items []*JobLog `json:"items"`
	// 总数
	TotalCount int `json:"totalCount"`
	// 分页信息
	PageInfo *OffsetPageInfo `json:"pageInfo"`
}

// 作业进度事件
type JobProgressEvent struct {
	// 作业 ID
	JobID uuid.UUID `json:"jobId"`
	// 关联的任务 ID
	TaskID uuid.UUID `json:"taskId"`
	// 关联的连接 ID
	ConnectionID uuid.UUID `json:"connectionId"`
	// 当前状态
	Status JobStatus `json:"status"`
	// 已传输文件数
	FilesTransferred int `json:"filesTransferred"`
	// 已传输字节数
	BytesTransferred int64 `json:"bytesTransferred"`
	// 总文件数（队列+已完成+进行中），会随扫描动态增加
	FilesTotal int `json:"filesTotal"`
	// 总字节数（队列大小+已传输+正在传输的总大小）
	BytesTotal int64 `json:"bytesTotal"`
	// 删除的文件数
	FilesDeleted int `json:"filesDeleted"`
	// 错误数量
	ErrorCount int `json:"errorCount"`
	// 已检查的文件数
	FilesChecked int `json:"filesChecked"`
	// 开始时间
	StartTime time.Time `json:"startTime"`
	// 结束时间
	EndTime *time.Time `json:"endTime,omitempty"`
}

// 作业查询命名空间
type JobQuery struct {
	// 获取作业列表
	List *JobConnection `json:"list"`
	// 获取单个作业
	Get *Job `json:"get,omitempty"`
	// 获取作业进度
	Progress *JobProgressEvent `json:"progress,omitempty"`
}

// 日志查询命名空间
type LogQuery struct {
	// 获取日志列表
	List *JobLogConnection `json:"list"`
}

type Mutation struct {
}

// 任务/连接 更新时嵌套的 Hook 变更列表项
type NestedUpdateHookInput struct {
	// Hook ID (为空时表示新增)
	ID *uuid.UUID `json:"id,omitempty"`
	// 是否删除该 Hook
	Delete *bool `json:"delete,omitempty"`
	// Hook 配置数据 (当 delete 为 false 时必填)
	Hook *HookInput `json:"hook,omitempty"`
}

// 偏移量分页信息
type OffsetPageInfo struct {
	// 当前页大小
	Limit int `json:"limit"`
	// 当前偏移量
	Offset int `json:"offset"`
	// 是否有下一页
	HasNextPage bool `json:"hasNextPage"`
	// 是否有上一页
	HasPreviousPage bool `json:"hasPreviousPage"`
}

// 选项示例
type OptionExample struct {
	// 示例值
	Value string `json:"value"`
	// 帮助说明
	Help *string `json:"help,omitempty"`
}

// 分页输入
type PaginationInput struct {
	// 每页数量（默认 20）
	Limit *int `json:"limit,omitempty"`
	// 偏移量（默认 0）
	Offset *int `json:"offset,omitempty"`
}

// 解析出的连接
type ParsedConnection struct {
	// 连接名称
	Name string `json:"name"`
	// 提供者类型
	Type string `json:"type"`
	// 配置参数
	Config map[string]string `json:"config"`
}

// 存储提供者
type Provider struct {
	// 提供者名称（如 onedrive, s3）
	Name string `json:"name"`
	// 描述
	Description string `json:"description"`
	// 前缀标识
	Prefix string `json:"prefix"`
	// 配置选项列表
	Options []*ProviderOption `json:"options"`
}

// 提供者配置选项
type ProviderOption struct {
	// 选项名称
	Name string `json:"name"`
	// 帮助文本
	Help string `json:"help"`
	// 是否必填
	Required bool `json:"required"`
	// 是否密码字段
	IsPassword bool `json:"isPassword"`
	// 默认值
	Default *string `json:"default,omitempty"`
	// 示例值列表
	Examples []*OptionExample `json:"examples,omitempty"`
	// 是否高级选项
	Advanced bool `json:"advanced"`
	// 选项分组
	Groups *string `json:"groups,omitempty"`
	// 是否独占选择（使用下拉框而非输入框）
	Exclusive bool `json:"exclusive"`
	// 选项数据类型
	Type string `json:"type"`
}

// 提供者查询命名空间
type ProviderQuery struct {
	// 获取所有存储提供者
	List []*Provider `json:"list"`
	// 获取单个提供者的配置选项
	Get *Provider `json:"get,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

// 同步任务
type Task struct {
	// UUID 主键
	ID uuid.UUID `json:"id"`
	// 任务名称
	Name string `json:"name"`
	// 本地源路径
	SourcePath string `json:"sourcePath"`
	// 远程目标路径
	RemotePath string `json:"remotePath"`
	// 同步方向
	Direction SyncDirection `json:"direction"`
	// Cron 调度表达式
	Schedule *string `json:"schedule,omitempty"`
	// 是否启用实时同步
	Realtime bool `json:"realtime"`
	// 任务是否启用
	Enabled bool `json:"enabled"`
	// 同步选项（JSON → 类型转换）
	Options *TaskSyncOptions `json:"options,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"createdAt"`
	// 更新时间
	UpdatedAt time.Time `json:"updatedAt"`
	// 关联的远程连接（ent edge）
	Connection *Connection `json:"connection"`
	// 作业历史（分页查询）
	Jobs *JobConnection `json:"jobs"`
	// 最近一次作业（计算字段）
	LatestJob *Job `json:"latestJob,omitempty"`
	// 关联的 Hooks 列表
	Hooks        []*Hook   `json:"hooks"`
	ConnectionID uuid.UUID `json:"-"`
}

// 任务分页连接
type TaskConnection struct {
	// 任务列表
	Items []*Task `json:"items"`
	// 总数
	TotalCount int `json:"totalCount"`
	// 分页信息
	PageInfo *OffsetPageInfo `json:"pageInfo"`
}

// 任务变更命名空间
type TaskMutation struct {
	// 创建任务（失败抛出 GraphQL error）
	Create *Task `json:"create"`
	// 更新任务（失败抛出 GraphQL error）
	Update *Task `json:"update"`
	// 删除任务（失败抛出 GraphQL error）
	Delete *Task `json:"delete"`
	// 运行任务（创建并启动作业，失败抛出 GraphQL error）
	Run *Job `json:"run"`
}

// 任务查询命名空间
type TaskQuery struct {
	// 获取任务列表
	List *TaskConnection `json:"list"`
	// 获取单个任务
	Get *Task `json:"get,omitempty"`
}

// 任务同步选项
type TaskSyncOptions struct {
	// 冲突解决策略（默认 NEWER，仅用于双向同步）
	ConflictResolution *ConflictResolution `json:"conflictResolution,omitempty"`
	// 文件过滤规则列表 - rclone filter 语法
	// 每个元素为一条规则，格式: "- pattern" (排除) 或 "+ pattern" (包含)
	// 规则按顺序匹配，第一个匹配的规则生效
	Filters []string `json:"filters,omitempty"`
	// 保留删除文件 - 仅单向同步有效
	// 启用后，同步不会删除目标端的多余文件
	NoDelete *bool `json:"noDelete,omitempty"`
	// 并行传输数量 - 范围 1-64
	// 为 null 时使用全局配置默认值
	Transfers *int `json:"transfers,omitempty"`
}

// 任务同步选项输入
type TaskSyncOptionsInput struct {
	// 冲突解决策略（默认 NEWER，仅用于双向同步）
	ConflictResolution *ConflictResolution `json:"conflictResolution,omitempty"`
	// 文件过滤规则列表 - rclone filter 语法
	Filters []string `json:"filters,omitempty"`
	// 保留删除文件 - 仅单向同步有效
	NoDelete *bool `json:"noDelete,omitempty"`
	// 并行传输数量 - 范围 1-64
	Transfers *int `json:"transfers,omitempty"`
}

// 测试连接输入（未保存的配置）
type TestConnectionInput struct {
	// 提供者类型
	Type string `json:"type"`
	// 配置参数
	Config map[string]string `json:"config"`
}

// 当前正在传输的文件项
type TransferItem struct {
	// 文件名称（含路径），如 "documents/report.pdf"
	Name string `json:"name"`
	// 文件总大小（字节）
	Size int64 `json:"size"`
	// 已传输字节数
	Bytes int64 `json:"bytes"`
	// 传输方向
	Direction TransferDirection `json:"direction"`
}

// 传输进度事件 - 当前正在传输的文件列表
type TransferProgressEvent struct {
	// 关联的作业 ID
	JobID uuid.UUID `json:"jobId"`
	// 关联的任务 ID
	TaskID uuid.UUID `json:"taskId"`
	// 关联的连接 ID
	ConnectionID uuid.UUID `json:"connectionId"`
	// 当前正在传输的文件列表
	Transfers []*TransferItem `json:"transfers"`
}

// 更新连接输入
type UpdateConnectionInput struct {
	// 连接名称
	Name *string `json:"name,omitempty"`
	// 配置参数
	Config map[string]string `json:"config,omitempty"`
	// 连接扩展选项（包含缓存配置）
	// 设置为 null 时保持不变
	Options *ConnectionOptionsInput `json:"options,omitempty"`
}

// 更新 Hook 输入
type UpdateHookInput struct {
	// 是否启用
	Enabled *bool `json:"enabled,omitempty"`
	// 执行优先级（升序，null 排最后）
	Priority *int `json:"priority,omitempty"`
	// 触发事件类型
	Event *HookEvent `json:"event,omitempty"`
	// Hook 类型（变更类型时需同时提供对应的配置）
	Type *HookType `json:"type,omitempty"`
	// 错误处理行为
	OnError *HookOnError `json:"onError,omitempty"`
	// Hook 配置（完整替换）
	Config *HookConfigInput `json:"config,omitempty"`
}

// 更新任务输入
type UpdateTaskInput struct {
	// 任务名称
	Name *string `json:"name,omitempty"`
	// 本地源路径
	SourcePath *string `json:"sourcePath,omitempty"`
	// 关联连接 ID
	ConnectionID *uuid.UUID `json:"connectionID,omitempty"`
	// 远程目标路径
	RemotePath *string `json:"remotePath,omitempty"`
	// 同步方向
	Direction *SyncDirection `json:"direction,omitempty"`
	// Cron 调度表达式
	Schedule *string `json:"schedule,omitempty"`
	// 是否启用实时同步
	Realtime *bool `json:"realtime,omitempty"`
	// 任务是否启用
	Enabled *bool `json:"enabled,omitempty"`
	// 同步选项
	Options *TaskSyncOptionsInput `json:"options,omitempty"`
	// 关联的 Hooks 变更列表
	Hooks []*NestedUpdateHookInput `json:"hooks,omitempty"`
}

// 冲突解决策略（仅用于双向同步）
type ConflictResolution string

const (
	// 保留较新文件，重命名较旧文件
	ConflictResolutionNewer ConflictResolution = "NEWER"
	// 保留本地文件，删除远程
	ConflictResolutionLocal ConflictResolution = "LOCAL"
	// 保留远程文件，删除本地
	ConflictResolutionRemote ConflictResolution = "REMOTE"
	// 保留两者，添加冲突后缀
	ConflictResolutionBoth ConflictResolution = "BOTH"
)

var AllConflictResolution = []ConflictResolution{
	ConflictResolutionNewer,
	ConflictResolutionLocal,
	ConflictResolutionRemote,
	ConflictResolutionBoth,
}

func (e ConflictResolution) IsValid() bool {
	switch e {
	case ConflictResolutionNewer, ConflictResolutionLocal, ConflictResolutionRemote, ConflictResolutionBoth:
		return true
	}
	return false
}

func (e ConflictResolution) String() string {
	return string(e)
}

func (e *ConflictResolution) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConflictResolution(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConflictResolution", str)
	}
	return nil
}

func (e ConflictResolution) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConflictResolution) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConflictResolution) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// 连接加载状态
type ConnectionLoadStatus string

const (
	// 已加载
	ConnectionLoadStatusLoaded ConnectionLoadStatus = "LOADED"
	// 加载中
	ConnectionLoadStatusLoading ConnectionLoadStatus = "LOADING"
	// 加载失败
	ConnectionLoadStatusError ConnectionLoadStatus = "ERROR"
)

var AllConnectionLoadStatus = []ConnectionLoadStatus{
	ConnectionLoadStatusLoaded,
	ConnectionLoadStatusLoading,
	ConnectionLoadStatusError,
}

func (e ConnectionLoadStatus) IsValid() bool {
	switch e {
	case ConnectionLoadStatusLoaded, ConnectionLoadStatusLoading, ConnectionLoadStatusError:
		return true
	}
	return false
}

func (e ConnectionLoadStatus) String() string {
	return string(e)
}

func (e *ConnectionLoadStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectionLoadStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectionLoadStatus", str)
	}
	return nil
}

func (e ConnectionLoadStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectionLoadStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectionLoadStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Hook 触发事件类型
type HookEvent string

const (
	// 任务开始执行前
	HookEventOnStart HookEvent = "ON_START"
	// 任务成功完成后
	HookEventOnSuccess HookEvent = "ON_SUCCESS"
	// 任务失败后
	HookEventOnFailure HookEvent = "ON_FAILURE"
	// 任务结束后（无论成功或失败，最后触发）
	HookEventOnEnd HookEvent = "ON_END"
)

var AllHookEvent = []HookEvent{
	HookEventOnStart,
	HookEventOnSuccess,
	HookEventOnFailure,
	HookEventOnEnd,
}

func (e HookEvent) IsValid() bool {
	switch e {
	case HookEventOnStart, HookEventOnSuccess, HookEventOnFailure, HookEventOnEnd:
		return true
	}
	return false
}

func (e HookEvent) String() string {
	return string(e)
}

func (e *HookEvent) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HookEvent(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HookEvent", str)
	}
	return nil
}

func (e HookEvent) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HookEvent) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HookEvent) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Hook 错误处理行为
type HookOnError string

const (
	// 忽略错误，继续执行后续 hooks
	HookOnErrorIgnore HookOnError = "IGNORE"
	// 停止任务，Job 标记为 CANCELLED，仅触发 on_end hook
	HookOnErrorCancel HookOnError = "CANCEL"
	// 停止任务，Job 标记为 FAILED，依次触发 on_failure 和 on_end hook
	HookOnErrorFatal HookOnError = "FATAL"
)

var AllHookOnError = []HookOnError{
	HookOnErrorIgnore,
	HookOnErrorCancel,
	HookOnErrorFatal,
}

func (e HookOnError) IsValid() bool {
	switch e {
	case HookOnErrorIgnore, HookOnErrorCancel, HookOnErrorFatal:
		return true
	}
	return false
}

func (e HookOnError) String() string {
	return string(e)
}

func (e *HookOnError) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HookOnError(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HookOnError", str)
	}
	return nil
}

func (e HookOnError) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HookOnError) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HookOnError) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Hook 类型
type HookType string

const (
	// HTTP 请求
	HookTypeHTTP HookType = "HTTP"
	// Shell 命令
	HookTypeCommand HookType = "COMMAND"
)

var AllHookType = []HookType{
	HookTypeHTTP,
	HookTypeCommand,
}

func (e HookType) IsValid() bool {
	switch e {
	case HookTypeHTTP, HookTypeCommand:
		return true
	}
	return false
}

func (e HookType) String() string {
	return string(e)
}

func (e *HookType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HookType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HookType", str)
	}
	return nil
}

func (e HookType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HookType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HookType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// 作业执行状态
type JobStatus string

const (
	// 等待执行
	JobStatusPending JobStatus = "PENDING"
	// 执行中
	JobStatusRunning JobStatus = "RUNNING"
	// 成功完成
	JobStatusSuccess JobStatus = "SUCCESS"
	// 执行失败
	JobStatusFailed JobStatus = "FAILED"
	// 已取消
	JobStatusCancelled JobStatus = "CANCELLED"
)

var AllJobStatus = []JobStatus{
	JobStatusPending,
	JobStatusRunning,
	JobStatusSuccess,
	JobStatusFailed,
	JobStatusCancelled,
}

func (e JobStatus) IsValid() bool {
	switch e {
	case JobStatusPending, JobStatusRunning, JobStatusSuccess, JobStatusFailed, JobStatusCancelled:
		return true
	}
	return false
}

func (e JobStatus) String() string {
	return string(e)
}

func (e *JobStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobStatus", str)
	}
	return nil
}

func (e JobStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// 作业触发方式
type JobTrigger string

const (
	// 手动触发
	JobTriggerManual JobTrigger = "MANUAL"
	// 定时触发
	JobTriggerSchedule JobTrigger = "SCHEDULE"
	// 实时触发（文件变更）
	JobTriggerRealtime JobTrigger = "REALTIME"
)

var AllJobTrigger = []JobTrigger{
	JobTriggerManual,
	JobTriggerSchedule,
	JobTriggerRealtime,
}

func (e JobTrigger) IsValid() bool {
	switch e {
	case JobTriggerManual, JobTriggerSchedule, JobTriggerRealtime:
		return true
	}
	return false
}

func (e JobTrigger) String() string {
	return string(e)
}

func (e *JobTrigger) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobTrigger(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobTrigger", str)
	}
	return nil
}

func (e JobTrigger) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobTrigger) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobTrigger) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// 日志操作类型
type LogAction string

const (
	// 上传文件
	LogActionUpload LogAction = "UPLOAD"
	// 下载文件
	LogActionDownload LogAction = "DOWNLOAD"
	// 删除文件
	LogActionDelete LogAction = "DELETE"
	// 移动文件
	LogActionMove LogAction = "MOVE"
	// 错误
	LogActionError LogAction = "ERROR"
	// 未知操作
	LogActionUnknown LogAction = "UNKNOWN"
	// Hook 执行记录
	LogActionHook LogAction = "HOOK"
)

var AllLogAction = []LogAction{
	LogActionUpload,
	LogActionDownload,
	LogActionDelete,
	LogActionMove,
	LogActionError,
	LogActionUnknown,
	LogActionHook,
}

func (e LogAction) IsValid() bool {
	switch e {
	case LogActionUpload, LogActionDownload, LogActionDelete, LogActionMove, LogActionError, LogActionUnknown, LogActionHook:
		return true
	}
	return false
}

func (e LogAction) String() string {
	return string(e)
}

func (e *LogAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LogAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LogAction", str)
	}
	return nil
}

func (e LogAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LogAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LogAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// 日志级别
type LogLevel string

const (
	LogLevelInfo    LogLevel = "INFO"
	LogLevelWarning LogLevel = "WARNING"
	LogLevelError   LogLevel = "ERROR"
)

var AllLogLevel = []LogLevel{
	LogLevelInfo,
	LogLevelWarning,
	LogLevelError,
}

func (e LogLevel) IsValid() bool {
	switch e {
	case LogLevelInfo, LogLevelWarning, LogLevelError:
		return true
	}
	return false
}

func (e LogLevel) String() string {
	return string(e)
}

func (e *LogLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LogLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LogLevel", str)
	}
	return nil
}

func (e LogLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LogLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LogLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// 同步方向
type SyncDirection string

const (
	// 本地上传到远程
	SyncDirectionUpload SyncDirection = "UPLOAD"
	// 远程下载到本地
	SyncDirectionDownload SyncDirection = "DOWNLOAD"
	// 双向同步
	SyncDirectionBidirectional SyncDirection = "BIDIRECTIONAL"
)

var AllSyncDirection = []SyncDirection{
	SyncDirectionUpload,
	SyncDirectionDownload,
	SyncDirectionBidirectional,
}

func (e SyncDirection) IsValid() bool {
	switch e {
	case SyncDirectionUpload, SyncDirectionDownload, SyncDirectionBidirectional:
		return true
	}
	return false
}

func (e SyncDirection) String() string {
	return string(e)
}

func (e *SyncDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SyncDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SyncDirection", str)
	}
	return nil
}

func (e SyncDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SyncDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SyncDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// 传输方向
type TransferDirection string

const (
	// 上传（本地 -> 远程）
	TransferDirectionUpload TransferDirection = "UPLOAD"
	// 下载（远程 -> 本地）
	TransferDirectionDownload TransferDirection = "DOWNLOAD"
)

var AllTransferDirection = []TransferDirection{
	TransferDirectionUpload,
	TransferDirectionDownload,
}

func (e TransferDirection) IsValid() bool {
	switch e {
	case TransferDirectionUpload, TransferDirectionDownload:
		return true
	}
	return false
}

func (e TransferDirection) String() string {
	return string(e)
}

func (e *TransferDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TransferDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TransferDirection", str)
	}
	return nil
}

func (e TransferDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TransferDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TransferDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
