// Code generated by ent, DO NOT EDIT.

package taskhook

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/xzzpig/rclone-sync/internal/api/graphql/model"
	"github.com/xzzpig/rclone-sync/internal/core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldLTE(FieldID, id))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldEQ(FieldEnabled, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldEQ(FieldPriority, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldEQ(FieldTaskID, v))
}

// ConnectionID applies equality check predicate on the "connection_id" field. It's identical to ConnectionIDEQ.
func ConnectionID(v uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldEQ(FieldConnectionID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldEQ(FieldUpdatedAt, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNEQ(FieldEnabled, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldLTE(FieldPriority, v))
}

// PriorityIsNil applies the IsNil predicate on the "priority" field.
func PriorityIsNil() predicate.TaskHook {
	return predicate.TaskHook(sql.FieldIsNull(FieldPriority))
}

// PriorityNotNil applies the NotNil predicate on the "priority" field.
func PriorityNotNil() predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNotNull(FieldPriority))
}

// EventEQ applies the EQ predicate on the "event" field.
func EventEQ(v model.HookEvent) predicate.TaskHook {
	vc := v
	return predicate.TaskHook(sql.FieldEQ(FieldEvent, vc))
}

// EventNEQ applies the NEQ predicate on the "event" field.
func EventNEQ(v model.HookEvent) predicate.TaskHook {
	vc := v
	return predicate.TaskHook(sql.FieldNEQ(FieldEvent, vc))
}

// EventIn applies the In predicate on the "event" field.
func EventIn(vs ...model.HookEvent) predicate.TaskHook {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TaskHook(sql.FieldIn(FieldEvent, v...))
}

// EventNotIn applies the NotIn predicate on the "event" field.
func EventNotIn(vs ...model.HookEvent) predicate.TaskHook {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TaskHook(sql.FieldNotIn(FieldEvent, v...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v model.HookType) predicate.TaskHook {
	vc := v
	return predicate.TaskHook(sql.FieldEQ(FieldType, vc))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v model.HookType) predicate.TaskHook {
	vc := v
	return predicate.TaskHook(sql.FieldNEQ(FieldType, vc))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...model.HookType) predicate.TaskHook {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TaskHook(sql.FieldIn(FieldType, v...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...model.HookType) predicate.TaskHook {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TaskHook(sql.FieldNotIn(FieldType, v...))
}

// OnErrorEQ applies the EQ predicate on the "on_error" field.
func OnErrorEQ(v model.HookOnError) predicate.TaskHook {
	vc := v
	return predicate.TaskHook(sql.FieldEQ(FieldOnError, vc))
}

// OnErrorNEQ applies the NEQ predicate on the "on_error" field.
func OnErrorNEQ(v model.HookOnError) predicate.TaskHook {
	vc := v
	return predicate.TaskHook(sql.FieldNEQ(FieldOnError, vc))
}

// OnErrorIn applies the In predicate on the "on_error" field.
func OnErrorIn(vs ...model.HookOnError) predicate.TaskHook {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TaskHook(sql.FieldIn(FieldOnError, v...))
}

// OnErrorNotIn applies the NotIn predicate on the "on_error" field.
func OnErrorNotIn(vs ...model.HookOnError) predicate.TaskHook {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TaskHook(sql.FieldNotIn(FieldOnError, v...))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDIsNil applies the IsNil predicate on the "task_id" field.
func TaskIDIsNil() predicate.TaskHook {
	return predicate.TaskHook(sql.FieldIsNull(FieldTaskID))
}

// TaskIDNotNil applies the NotNil predicate on the "task_id" field.
func TaskIDNotNil() predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNotNull(FieldTaskID))
}

// ConnectionIDEQ applies the EQ predicate on the "connection_id" field.
func ConnectionIDEQ(v uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldEQ(FieldConnectionID, v))
}

// ConnectionIDNEQ applies the NEQ predicate on the "connection_id" field.
func ConnectionIDNEQ(v uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNEQ(FieldConnectionID, v))
}

// ConnectionIDIn applies the In predicate on the "connection_id" field.
func ConnectionIDIn(vs ...uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldIn(FieldConnectionID, vs...))
}

// ConnectionIDNotIn applies the NotIn predicate on the "connection_id" field.
func ConnectionIDNotIn(vs ...uuid.UUID) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNotIn(FieldConnectionID, vs...))
}

// ConnectionIDIsNil applies the IsNil predicate on the "connection_id" field.
func ConnectionIDIsNil() predicate.TaskHook {
	return predicate.TaskHook(sql.FieldIsNull(FieldConnectionID))
}

// ConnectionIDNotNil applies the NotNil predicate on the "connection_id" field.
func ConnectionIDNotNil() predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNotNull(FieldConnectionID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TaskHook {
	return predicate.TaskHook(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.TaskHook {
	return predicate.TaskHook(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.TaskHook {
	return predicate.TaskHook(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasConnection applies the HasEdge predicate on the "connection" edge.
func HasConnection() predicate.TaskHook {
	return predicate.TaskHook(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ConnectionTable, ConnectionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConnectionWith applies the HasEdge predicate on the "connection" edge with a given conditions (other predicates).
func HasConnectionWith(preds ...predicate.Connection) predicate.TaskHook {
	return predicate.TaskHook(func(s *sql.Selector) {
		step := newConnectionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TaskHook) predicate.TaskHook {
	return predicate.TaskHook(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TaskHook) predicate.TaskHook {
	return predicate.TaskHook(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TaskHook) predicate.TaskHook {
	return predicate.TaskHook(sql.NotPredicates(p))
}
