package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/xzzpig/rclone-sync/internal/api/graphql/model"
)

// AppConfig is the resolver for the appConfig field.
func (r *queryResolver) AppConfig(ctx context.Context) (*model.AppConfig, error) {
	enabled := true
	if r.deps.Config != nil {
		enabled = r.deps.Config.App.Hook.Enabled
	}
	return &model.AppConfig{
		Hook: &model.AppHookConfig{
			Enabled: enabled,
		},
	}, nil
}
