package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/google/uuid"
	"github.com/xzzpig/rclone-sync/internal/api/graphql/dataloader"
	"github.com/xzzpig/rclone-sync/internal/api/graphql/generated"
	"github.com/xzzpig/rclone-sync/internal/api/graphql/model"
	"github.com/xzzpig/rclone-sync/internal/core/hook"
	"github.com/xzzpig/rclone-sync/internal/i18n"
)

// Hooks is the resolver for the hooks field.
func (r *connectionResolver) Hooks(ctx context.Context, obj *model.Connection) ([]*model.Hook, error) {
	entHooks, err := r.deps.HookQuery.ListHooks(ctx, nil, &obj.ID, nil)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Hook, len(entHooks))
	for i, h := range entHooks {
		result[i] = entHookToModel(h)
	}
	return result, nil
}

// Task is the resolver for the task field.
func (r *hookResolver) Task(ctx context.Context, obj *model.Hook) (*model.Task, error) {
	if obj.TaskID == nil {
		return nil, nil
	}
	loaders := dataloader.For(ctx)
	entTask, err := loaders.TaskLoader.Load(ctx, *obj.TaskID)
	if err != nil {
		return nil, nil //nolint:nilerr // Return nil if task not found
	}
	return entTaskToModel(entTask), nil
}

// Connection is the resolver for the connection field.
func (r *hookResolver) Connection(ctx context.Context, obj *model.Hook) (*model.Connection, error) {
	if obj.ConnectionID == nil {
		return nil, nil
	}
	loaders := dataloader.For(ctx)
	entConn, err := loaders.ConnectionLoader.Load(ctx, *obj.ConnectionID)
	if err != nil {
		return nil, nil //nolint:nilerr // Return nil if connection not found
	}
	return entConnectionToModel(entConn), nil
}

// Create is the resolver for the create field.
func (r *hookMutationResolver) Create(ctx context.Context, obj *model.HookMutation, taskID *uuid.UUID, connectionID *uuid.UUID, input model.HookInput) (*model.Hook, error) {
	if taskID == nil && connectionID == nil {
		return nil, i18n.NewI18nError(i18n.ErrInvalidInput).WithCause(errMutualExclusiveFields)
	}
	if taskID != nil && connectionID != nil {
		return nil, i18n.NewI18nError(i18n.ErrInvalidInput).WithCause(errMutualExclusiveFields)
	}

	// Validate configuration
	if err := hook.ValidateHookConfig(input.Config, input.Type); err != nil {
		return nil, i18n.NewI18nError(i18n.ErrInvalidInput).WithCause(err)
	}

	entHook, err := r.deps.HookQuery.CreateHook(ctx, taskID, connectionID, input)
	if err != nil {
		return nil, err
	}

	return entHookToModel(entHook), nil
}

// Update is the resolver for the update field.
func (r *hookMutationResolver) Update(ctx context.Context, obj *model.HookMutation, id uuid.UUID, input model.UpdateHookInput) (*model.Hook, error) {
	if input.Config != nil {
		// For update, we might need existing type to validate properly
		hookType := input.Type
		if hookType == nil {
			existing, err := r.deps.HookQuery.GetHook(ctx, id)
			if err != nil {
				return nil, err
			}
			t := existing.Type
			hookType = &t
		}

		if err := hook.ValidateHookConfig(input.Config, *hookType); err != nil {
			return nil, i18n.NewI18nError(i18n.ErrInvalidInput).WithCause(err)
		}
	}

	entHook, err := r.deps.HookQuery.UpdateHook(ctx, id, input)
	if err != nil {
		return nil, err
	}

	return entHookToModel(entHook), nil
}

// Delete is the resolver for the delete field.
func (r *hookMutationResolver) Delete(ctx context.Context, obj *model.HookMutation, id uuid.UUID) (*model.Hook, error) {
	entHook, err := r.deps.HookQuery.DeleteHook(ctx, id)
	if err != nil {
		return nil, err
	}

	return entHookToModel(entHook), nil
}

// List is the resolver for the list field.
func (r *hookQueryResolver) List(ctx context.Context, obj *model.HookQuery, taskID *uuid.UUID, connectionID *uuid.UUID, event *model.HookEvent) ([]*model.Hook, error) {
	if taskID == nil && connectionID == nil {
		return nil, i18n.NewI18nError(i18n.ErrInvalidInput).WithCause(errAtLeastOneRequired)
	}

	entHooks, err := r.deps.HookQuery.ListHooks(ctx, taskID, connectionID, event)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Hook, len(entHooks))
	for i, h := range entHooks {
		result[i] = entHookToModel(h)
	}
	return result, nil
}

// Get is the resolver for the get field.
func (r *hookQueryResolver) Get(ctx context.Context, obj *model.HookQuery, id uuid.UUID) (*model.Hook, error) {
	entHook, err := r.deps.HookQuery.GetHook(ctx, id)
	if err != nil {
		return nil, nil //nolint:nilerr // Return nil if not found
	}
	return entHookToModel(entHook), nil
}

// Hook is the resolver for the hook field.
func (r *mutationResolver) Hook(ctx context.Context) (*model.HookMutation, error) {
	return &model.HookMutation{}, nil
}

// Hook is the resolver for the hook field.
func (r *queryResolver) Hook(ctx context.Context) (*model.HookQuery, error) {
	return &model.HookQuery{}, nil
}

// Hooks is the resolver for the hooks field.
func (r *taskResolver) Hooks(ctx context.Context, obj *model.Task) ([]*model.Hook, error) {
	entHooks, err := r.deps.HookQuery.ListHooks(ctx, &obj.ID, nil, nil)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Hook, len(entHooks))
	for i, h := range entHooks {
		result[i] = entHookToModel(h)
	}
	return result, nil
}

// Hook returns generated.HookResolver implementation.
func (r *Resolver) Hook() generated.HookResolver { return &hookResolver{r} }

// HookMutation returns generated.HookMutationResolver implementation.
func (r *Resolver) HookMutation() generated.HookMutationResolver { return &hookMutationResolver{r} }

// HookQuery returns generated.HookQueryResolver implementation.
func (r *Resolver) HookQuery() generated.HookQueryResolver { return &hookQueryResolver{r} }

type hookResolver struct{ *Resolver }
type hookMutationResolver struct{ *Resolver }
type hookQueryResolver struct{ *Resolver }
