// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/xzzpig/rclone-sync/internal/core/ent/job"
	"github.com/xzzpig/rclone-sync/internal/core/ent/joblog"
	"github.com/xzzpig/rclone-sync/internal/core/ent/task"
)

// JobCreate is the builder for creating a Job entity.
type JobCreate struct {
	config
	mutation *JobMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (jc *JobCreate) SetStatus(j job.Status) *JobCreate {
	jc.mutation.SetStatus(j)
	return jc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (jc *JobCreate) SetNillableStatus(j *job.Status) *JobCreate {
	if j != nil {
		jc.SetStatus(*j)
	}
	return jc
}

// SetTrigger sets the "trigger" field.
func (jc *JobCreate) SetTrigger(j job.Trigger) *JobCreate {
	jc.mutation.SetTrigger(j)
	return jc
}

// SetStartTime sets the "start_time" field.
func (jc *JobCreate) SetStartTime(t time.Time) *JobCreate {
	jc.mutation.SetStartTime(t)
	return jc
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (jc *JobCreate) SetNillableStartTime(t *time.Time) *JobCreate {
	if t != nil {
		jc.SetStartTime(*t)
	}
	return jc
}

// SetEndTime sets the "end_time" field.
func (jc *JobCreate) SetEndTime(t time.Time) *JobCreate {
	jc.mutation.SetEndTime(t)
	return jc
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (jc *JobCreate) SetNillableEndTime(t *time.Time) *JobCreate {
	if t != nil {
		jc.SetEndTime(*t)
	}
	return jc
}

// SetFilesTransferred sets the "files_transferred" field.
func (jc *JobCreate) SetFilesTransferred(i int) *JobCreate {
	jc.mutation.SetFilesTransferred(i)
	return jc
}

// SetNillableFilesTransferred sets the "files_transferred" field if the given value is not nil.
func (jc *JobCreate) SetNillableFilesTransferred(i *int) *JobCreate {
	if i != nil {
		jc.SetFilesTransferred(*i)
	}
	return jc
}

// SetBytesTransferred sets the "bytes_transferred" field.
func (jc *JobCreate) SetBytesTransferred(i int64) *JobCreate {
	jc.mutation.SetBytesTransferred(i)
	return jc
}

// SetNillableBytesTransferred sets the "bytes_transferred" field if the given value is not nil.
func (jc *JobCreate) SetNillableBytesTransferred(i *int64) *JobCreate {
	if i != nil {
		jc.SetBytesTransferred(*i)
	}
	return jc
}

// SetErrors sets the "errors" field.
func (jc *JobCreate) SetErrors(s string) *JobCreate {
	jc.mutation.SetErrors(s)
	return jc
}

// SetNillableErrors sets the "errors" field if the given value is not nil.
func (jc *JobCreate) SetNillableErrors(s *string) *JobCreate {
	if s != nil {
		jc.SetErrors(*s)
	}
	return jc
}

// SetID sets the "id" field.
func (jc *JobCreate) SetID(u uuid.UUID) *JobCreate {
	jc.mutation.SetID(u)
	return jc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (jc *JobCreate) SetNillableID(u *uuid.UUID) *JobCreate {
	if u != nil {
		jc.SetID(*u)
	}
	return jc
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (jc *JobCreate) SetTaskID(id uuid.UUID) *JobCreate {
	jc.mutation.SetTaskID(id)
	return jc
}

// SetTask sets the "task" edge to the Task entity.
func (jc *JobCreate) SetTask(t *Task) *JobCreate {
	return jc.SetTaskID(t.ID)
}

// AddLogIDs adds the "logs" edge to the JobLog entity by IDs.
func (jc *JobCreate) AddLogIDs(ids ...int) *JobCreate {
	jc.mutation.AddLogIDs(ids...)
	return jc
}

// AddLogs adds the "logs" edges to the JobLog entity.
func (jc *JobCreate) AddLogs(j ...*JobLog) *JobCreate {
	ids := make([]int, len(j))
	for i := range j {
		ids[i] = j[i].ID
	}
	return jc.AddLogIDs(ids...)
}

// Mutation returns the JobMutation object of the builder.
func (jc *JobCreate) Mutation() *JobMutation {
	return jc.mutation
}

// Save creates the Job in the database.
func (jc *JobCreate) Save(ctx context.Context) (*Job, error) {
	jc.defaults()
	return withHooks(ctx, jc.sqlSave, jc.mutation, jc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (jc *JobCreate) SaveX(ctx context.Context) *Job {
	v, err := jc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jc *JobCreate) Exec(ctx context.Context) error {
	_, err := jc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jc *JobCreate) ExecX(ctx context.Context) {
	if err := jc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (jc *JobCreate) defaults() {
	if _, ok := jc.mutation.Status(); !ok {
		v := job.DefaultStatus
		jc.mutation.SetStatus(v)
	}
	if _, ok := jc.mutation.StartTime(); !ok {
		v := job.DefaultStartTime()
		jc.mutation.SetStartTime(v)
	}
	if _, ok := jc.mutation.FilesTransferred(); !ok {
		v := job.DefaultFilesTransferred
		jc.mutation.SetFilesTransferred(v)
	}
	if _, ok := jc.mutation.BytesTransferred(); !ok {
		v := job.DefaultBytesTransferred
		jc.mutation.SetBytesTransferred(v)
	}
	if _, ok := jc.mutation.ID(); !ok {
		v := job.DefaultID()
		jc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jc *JobCreate) check() error {
	if _, ok := jc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Job.status"`)}
	}
	if v, ok := jc.mutation.Status(); ok {
		if err := job.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Job.status": %w`, err)}
		}
	}
	if _, ok := jc.mutation.Trigger(); !ok {
		return &ValidationError{Name: "trigger", err: errors.New(`ent: missing required field "Job.trigger"`)}
	}
	if v, ok := jc.mutation.Trigger(); ok {
		if err := job.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "Job.trigger": %w`, err)}
		}
	}
	if _, ok := jc.mutation.StartTime(); !ok {
		return &ValidationError{Name: "start_time", err: errors.New(`ent: missing required field "Job.start_time"`)}
	}
	if _, ok := jc.mutation.FilesTransferred(); !ok {
		return &ValidationError{Name: "files_transferred", err: errors.New(`ent: missing required field "Job.files_transferred"`)}
	}
	if _, ok := jc.mutation.BytesTransferred(); !ok {
		return &ValidationError{Name: "bytes_transferred", err: errors.New(`ent: missing required field "Job.bytes_transferred"`)}
	}
	if len(jc.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "Job.task"`)}
	}
	return nil
}

func (jc *JobCreate) sqlSave(ctx context.Context) (*Job, error) {
	if err := jc.check(); err != nil {
		return nil, err
	}
	_node, _spec := jc.createSpec()
	if err := sqlgraph.CreateNode(ctx, jc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	jc.mutation.id = &_node.ID
	jc.mutation.done = true
	return _node, nil
}

func (jc *JobCreate) createSpec() (*Job, *sqlgraph.CreateSpec) {
	var (
		_node = &Job{config: jc.config}
		_spec = sqlgraph.NewCreateSpec(job.Table, sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID))
	)
	if id, ok := jc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := jc.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := jc.mutation.Trigger(); ok {
		_spec.SetField(job.FieldTrigger, field.TypeEnum, value)
		_node.Trigger = value
	}
	if value, ok := jc.mutation.StartTime(); ok {
		_spec.SetField(job.FieldStartTime, field.TypeTime, value)
		_node.StartTime = value
	}
	if value, ok := jc.mutation.EndTime(); ok {
		_spec.SetField(job.FieldEndTime, field.TypeTime, value)
		_node.EndTime = value
	}
	if value, ok := jc.mutation.FilesTransferred(); ok {
		_spec.SetField(job.FieldFilesTransferred, field.TypeInt, value)
		_node.FilesTransferred = value
	}
	if value, ok := jc.mutation.BytesTransferred(); ok {
		_spec.SetField(job.FieldBytesTransferred, field.TypeInt64, value)
		_node.BytesTransferred = value
	}
	if value, ok := jc.mutation.Errors(); ok {
		_spec.SetField(job.FieldErrors, field.TypeString, value)
		_node.Errors = value
	}
	if nodes := jc.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   job.TaskTable,
			Columns: []string{job.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.task_jobs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := jc.mutation.LogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   job.LogsTable,
			Columns: []string{job.LogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(joblog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// JobCreateBulk is the builder for creating many Job entities in bulk.
type JobCreateBulk struct {
	config
	err      error
	builders []*JobCreate
}

// Save creates the Job entities in the database.
func (jcb *JobCreateBulk) Save(ctx context.Context) ([]*Job, error) {
	if jcb.err != nil {
		return nil, jcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(jcb.builders))
	nodes := make([]*Job, len(jcb.builders))
	mutators := make([]Mutator, len(jcb.builders))
	for i := range jcb.builders {
		func(i int, root context.Context) {
			builder := jcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, jcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, jcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, jcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (jcb *JobCreateBulk) SaveX(ctx context.Context) []*Job {
	v, err := jcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jcb *JobCreateBulk) Exec(ctx context.Context) error {
	_, err := jcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jcb *JobCreateBulk) ExecX(ctx context.Context) {
	if err := jcb.Exec(ctx); err != nil {
		panic(err)
	}
}
