// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/xzzpig/rclone-sync/internal/core/ent/job"
	"github.com/xzzpig/rclone-sync/internal/core/ent/joblog"
	"github.com/xzzpig/rclone-sync/internal/core/ent/task"
)

// JobCreate is the builder for creating a Job entity.
type JobCreate struct {
	config
	mutation *JobMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *JobCreate) SetStatus(v job.Status) *JobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *JobCreate) SetNillableStatus(v *job.Status) *JobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTrigger sets the "trigger" field.
func (_c *JobCreate) SetTrigger(v job.Trigger) *JobCreate {
	_c.mutation.SetTrigger(v)
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *JobCreate) SetStartTime(v time.Time) *JobCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_c *JobCreate) SetNillableStartTime(v *time.Time) *JobCreate {
	if v != nil {
		_c.SetStartTime(*v)
	}
	return _c
}

// SetEndTime sets the "end_time" field.
func (_c *JobCreate) SetEndTime(v time.Time) *JobCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_c *JobCreate) SetNillableEndTime(v *time.Time) *JobCreate {
	if v != nil {
		_c.SetEndTime(*v)
	}
	return _c
}

// SetFilesTransferred sets the "files_transferred" field.
func (_c *JobCreate) SetFilesTransferred(v int) *JobCreate {
	_c.mutation.SetFilesTransferred(v)
	return _c
}

// SetNillableFilesTransferred sets the "files_transferred" field if the given value is not nil.
func (_c *JobCreate) SetNillableFilesTransferred(v *int) *JobCreate {
	if v != nil {
		_c.SetFilesTransferred(*v)
	}
	return _c
}

// SetBytesTransferred sets the "bytes_transferred" field.
func (_c *JobCreate) SetBytesTransferred(v int64) *JobCreate {
	_c.mutation.SetBytesTransferred(v)
	return _c
}

// SetNillableBytesTransferred sets the "bytes_transferred" field if the given value is not nil.
func (_c *JobCreate) SetNillableBytesTransferred(v *int64) *JobCreate {
	if v != nil {
		_c.SetBytesTransferred(*v)
	}
	return _c
}

// SetErrors sets the "errors" field.
func (_c *JobCreate) SetErrors(v string) *JobCreate {
	_c.mutation.SetErrors(v)
	return _c
}

// SetNillableErrors sets the "errors" field if the given value is not nil.
func (_c *JobCreate) SetNillableErrors(v *string) *JobCreate {
	if v != nil {
		_c.SetErrors(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *JobCreate) SetID(v uuid.UUID) *JobCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *JobCreate) SetNillableID(v *uuid.UUID) *JobCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_c *JobCreate) SetTaskID(id uuid.UUID) *JobCreate {
	_c.mutation.SetTaskID(id)
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *JobCreate) SetTask(v *Task) *JobCreate {
	return _c.SetTaskID(v.ID)
}

// AddLogIDs adds the "logs" edge to the JobLog entity by IDs.
func (_c *JobCreate) AddLogIDs(ids ...int) *JobCreate {
	_c.mutation.AddLogIDs(ids...)
	return _c
}

// AddLogs adds the "logs" edges to the JobLog entity.
func (_c *JobCreate) AddLogs(v ...*JobLog) *JobCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLogIDs(ids...)
}

// Mutation returns the JobMutation object of the builder.
func (_c *JobCreate) Mutation() *JobMutation {
	return _c.mutation
}

// Save creates the Job in the database.
func (_c *JobCreate) Save(ctx context.Context) (*Job, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *JobCreate) SaveX(ctx context.Context) *Job {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *JobCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := job.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.StartTime(); !ok {
		v := job.DefaultStartTime()
		_c.mutation.SetStartTime(v)
	}
	if _, ok := _c.mutation.FilesTransferred(); !ok {
		v := job.DefaultFilesTransferred
		_c.mutation.SetFilesTransferred(v)
	}
	if _, ok := _c.mutation.BytesTransferred(); !ok {
		v := job.DefaultBytesTransferred
		_c.mutation.SetBytesTransferred(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := job.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *JobCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Job.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := job.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Job.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Trigger(); !ok {
		return &ValidationError{Name: "trigger", err: errors.New(`ent: missing required field "Job.trigger"`)}
	}
	if v, ok := _c.mutation.Trigger(); ok {
		if err := job.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "Job.trigger": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartTime(); !ok {
		return &ValidationError{Name: "start_time", err: errors.New(`ent: missing required field "Job.start_time"`)}
	}
	if _, ok := _c.mutation.FilesTransferred(); !ok {
		return &ValidationError{Name: "files_transferred", err: errors.New(`ent: missing required field "Job.files_transferred"`)}
	}
	if _, ok := _c.mutation.BytesTransferred(); !ok {
		return &ValidationError{Name: "bytes_transferred", err: errors.New(`ent: missing required field "Job.bytes_transferred"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "Job.task"`)}
	}
	return nil
}

func (_c *JobCreate) sqlSave(ctx context.Context) (*Job, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *JobCreate) createSpec() (*Job, *sqlgraph.CreateSpec) {
	var (
		_node = &Job{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(job.Table, sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Trigger(); ok {
		_spec.SetField(job.FieldTrigger, field.TypeEnum, value)
		_node.Trigger = value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(job.FieldStartTime, field.TypeTime, value)
		_node.StartTime = value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(job.FieldEndTime, field.TypeTime, value)
		_node.EndTime = value
	}
	if value, ok := _c.mutation.FilesTransferred(); ok {
		_spec.SetField(job.FieldFilesTransferred, field.TypeInt, value)
		_node.FilesTransferred = value
	}
	if value, ok := _c.mutation.BytesTransferred(); ok {
		_spec.SetField(job.FieldBytesTransferred, field.TypeInt64, value)
		_node.BytesTransferred = value
	}
	if value, ok := _c.mutation.Errors(); ok {
		_spec.SetField(job.FieldErrors, field.TypeString, value)
		_node.Errors = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   job.TaskTable,
			Columns: []string{job.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.task_jobs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   job.LogsTable,
			Columns: []string{job.LogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(joblog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// JobCreateBulk is the builder for creating many Job entities in bulk.
type JobCreateBulk struct {
	config
	err      error
	builders []*JobCreate
}

// Save creates the Job entities in the database.
func (_c *JobCreateBulk) Save(ctx context.Context) ([]*Job, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Job, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *JobCreateBulk) SaveX(ctx context.Context) []*Job {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
