// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/xzzpig/rclone-sync/internal/core/ent/job"
	"github.com/xzzpig/rclone-sync/internal/core/ent/joblog"
	"github.com/xzzpig/rclone-sync/internal/core/ent/predicate"
)

// JobLogUpdate is the builder for updating JobLog entities.
type JobLogUpdate struct {
	config
	hooks    []Hook
	mutation *JobLogMutation
}

// Where appends a list predicates to the JobLogUpdate builder.
func (jlu *JobLogUpdate) Where(ps ...predicate.JobLog) *JobLogUpdate {
	jlu.mutation.Where(ps...)
	return jlu
}

// SetLevel sets the "level" field.
func (jlu *JobLogUpdate) SetLevel(j joblog.Level) *JobLogUpdate {
	jlu.mutation.SetLevel(j)
	return jlu
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (jlu *JobLogUpdate) SetNillableLevel(j *joblog.Level) *JobLogUpdate {
	if j != nil {
		jlu.SetLevel(*j)
	}
	return jlu
}

// SetTime sets the "time" field.
func (jlu *JobLogUpdate) SetTime(t time.Time) *JobLogUpdate {
	jlu.mutation.SetTime(t)
	return jlu
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (jlu *JobLogUpdate) SetNillableTime(t *time.Time) *JobLogUpdate {
	if t != nil {
		jlu.SetTime(*t)
	}
	return jlu
}

// SetPath sets the "path" field.
func (jlu *JobLogUpdate) SetPath(s string) *JobLogUpdate {
	jlu.mutation.SetPath(s)
	return jlu
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (jlu *JobLogUpdate) SetNillablePath(s *string) *JobLogUpdate {
	if s != nil {
		jlu.SetPath(*s)
	}
	return jlu
}

// ClearPath clears the value of the "path" field.
func (jlu *JobLogUpdate) ClearPath() *JobLogUpdate {
	jlu.mutation.ClearPath()
	return jlu
}

// SetWhat sets the "what" field.
func (jlu *JobLogUpdate) SetWhat(j joblog.What) *JobLogUpdate {
	jlu.mutation.SetWhat(j)
	return jlu
}

// SetNillableWhat sets the "what" field if the given value is not nil.
func (jlu *JobLogUpdate) SetNillableWhat(j *joblog.What) *JobLogUpdate {
	if j != nil {
		jlu.SetWhat(*j)
	}
	return jlu
}

// SetSize sets the "size" field.
func (jlu *JobLogUpdate) SetSize(i int64) *JobLogUpdate {
	jlu.mutation.ResetSize()
	jlu.mutation.SetSize(i)
	return jlu
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (jlu *JobLogUpdate) SetNillableSize(i *int64) *JobLogUpdate {
	if i != nil {
		jlu.SetSize(*i)
	}
	return jlu
}

// AddSize adds i to the "size" field.
func (jlu *JobLogUpdate) AddSize(i int64) *JobLogUpdate {
	jlu.mutation.AddSize(i)
	return jlu
}

// ClearSize clears the value of the "size" field.
func (jlu *JobLogUpdate) ClearSize() *JobLogUpdate {
	jlu.mutation.ClearSize()
	return jlu
}

// SetJobID sets the "job" edge to the Job entity by ID.
func (jlu *JobLogUpdate) SetJobID(id uuid.UUID) *JobLogUpdate {
	jlu.mutation.SetJobID(id)
	return jlu
}

// SetJob sets the "job" edge to the Job entity.
func (jlu *JobLogUpdate) SetJob(j *Job) *JobLogUpdate {
	return jlu.SetJobID(j.ID)
}

// Mutation returns the JobLogMutation object of the builder.
func (jlu *JobLogUpdate) Mutation() *JobLogMutation {
	return jlu.mutation
}

// ClearJob clears the "job" edge to the Job entity.
func (jlu *JobLogUpdate) ClearJob() *JobLogUpdate {
	jlu.mutation.ClearJob()
	return jlu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (jlu *JobLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, jlu.sqlSave, jlu.mutation, jlu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (jlu *JobLogUpdate) SaveX(ctx context.Context) int {
	affected, err := jlu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (jlu *JobLogUpdate) Exec(ctx context.Context) error {
	_, err := jlu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jlu *JobLogUpdate) ExecX(ctx context.Context) {
	if err := jlu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jlu *JobLogUpdate) check() error {
	if v, ok := jlu.mutation.Level(); ok {
		if err := joblog.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "JobLog.level": %w`, err)}
		}
	}
	if v, ok := jlu.mutation.What(); ok {
		if err := joblog.WhatValidator(v); err != nil {
			return &ValidationError{Name: "what", err: fmt.Errorf(`ent: validator failed for field "JobLog.what": %w`, err)}
		}
	}
	if jlu.mutation.JobCleared() && len(jlu.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "JobLog.job"`)
	}
	return nil
}

func (jlu *JobLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := jlu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(joblog.Table, joblog.Columns, sqlgraph.NewFieldSpec(joblog.FieldID, field.TypeInt))
	if ps := jlu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := jlu.mutation.Level(); ok {
		_spec.SetField(joblog.FieldLevel, field.TypeEnum, value)
	}
	if value, ok := jlu.mutation.Time(); ok {
		_spec.SetField(joblog.FieldTime, field.TypeTime, value)
	}
	if value, ok := jlu.mutation.Path(); ok {
		_spec.SetField(joblog.FieldPath, field.TypeString, value)
	}
	if jlu.mutation.PathCleared() {
		_spec.ClearField(joblog.FieldPath, field.TypeString)
	}
	if value, ok := jlu.mutation.What(); ok {
		_spec.SetField(joblog.FieldWhat, field.TypeEnum, value)
	}
	if value, ok := jlu.mutation.Size(); ok {
		_spec.SetField(joblog.FieldSize, field.TypeInt64, value)
	}
	if value, ok := jlu.mutation.AddedSize(); ok {
		_spec.AddField(joblog.FieldSize, field.TypeInt64, value)
	}
	if jlu.mutation.SizeCleared() {
		_spec.ClearField(joblog.FieldSize, field.TypeInt64)
	}
	if jlu.mutation.JobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   joblog.JobTable,
			Columns: []string{joblog.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := jlu.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   joblog.JobTable,
			Columns: []string{joblog.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, jlu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{joblog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	jlu.mutation.done = true
	return n, nil
}

// JobLogUpdateOne is the builder for updating a single JobLog entity.
type JobLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobLogMutation
}

// SetLevel sets the "level" field.
func (jluo *JobLogUpdateOne) SetLevel(j joblog.Level) *JobLogUpdateOne {
	jluo.mutation.SetLevel(j)
	return jluo
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (jluo *JobLogUpdateOne) SetNillableLevel(j *joblog.Level) *JobLogUpdateOne {
	if j != nil {
		jluo.SetLevel(*j)
	}
	return jluo
}

// SetTime sets the "time" field.
func (jluo *JobLogUpdateOne) SetTime(t time.Time) *JobLogUpdateOne {
	jluo.mutation.SetTime(t)
	return jluo
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (jluo *JobLogUpdateOne) SetNillableTime(t *time.Time) *JobLogUpdateOne {
	if t != nil {
		jluo.SetTime(*t)
	}
	return jluo
}

// SetPath sets the "path" field.
func (jluo *JobLogUpdateOne) SetPath(s string) *JobLogUpdateOne {
	jluo.mutation.SetPath(s)
	return jluo
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (jluo *JobLogUpdateOne) SetNillablePath(s *string) *JobLogUpdateOne {
	if s != nil {
		jluo.SetPath(*s)
	}
	return jluo
}

// ClearPath clears the value of the "path" field.
func (jluo *JobLogUpdateOne) ClearPath() *JobLogUpdateOne {
	jluo.mutation.ClearPath()
	return jluo
}

// SetWhat sets the "what" field.
func (jluo *JobLogUpdateOne) SetWhat(j joblog.What) *JobLogUpdateOne {
	jluo.mutation.SetWhat(j)
	return jluo
}

// SetNillableWhat sets the "what" field if the given value is not nil.
func (jluo *JobLogUpdateOne) SetNillableWhat(j *joblog.What) *JobLogUpdateOne {
	if j != nil {
		jluo.SetWhat(*j)
	}
	return jluo
}

// SetSize sets the "size" field.
func (jluo *JobLogUpdateOne) SetSize(i int64) *JobLogUpdateOne {
	jluo.mutation.ResetSize()
	jluo.mutation.SetSize(i)
	return jluo
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (jluo *JobLogUpdateOne) SetNillableSize(i *int64) *JobLogUpdateOne {
	if i != nil {
		jluo.SetSize(*i)
	}
	return jluo
}

// AddSize adds i to the "size" field.
func (jluo *JobLogUpdateOne) AddSize(i int64) *JobLogUpdateOne {
	jluo.mutation.AddSize(i)
	return jluo
}

// ClearSize clears the value of the "size" field.
func (jluo *JobLogUpdateOne) ClearSize() *JobLogUpdateOne {
	jluo.mutation.ClearSize()
	return jluo
}

// SetJobID sets the "job" edge to the Job entity by ID.
func (jluo *JobLogUpdateOne) SetJobID(id uuid.UUID) *JobLogUpdateOne {
	jluo.mutation.SetJobID(id)
	return jluo
}

// SetJob sets the "job" edge to the Job entity.
func (jluo *JobLogUpdateOne) SetJob(j *Job) *JobLogUpdateOne {
	return jluo.SetJobID(j.ID)
}

// Mutation returns the JobLogMutation object of the builder.
func (jluo *JobLogUpdateOne) Mutation() *JobLogMutation {
	return jluo.mutation
}

// ClearJob clears the "job" edge to the Job entity.
func (jluo *JobLogUpdateOne) ClearJob() *JobLogUpdateOne {
	jluo.mutation.ClearJob()
	return jluo
}

// Where appends a list predicates to the JobLogUpdate builder.
func (jluo *JobLogUpdateOne) Where(ps ...predicate.JobLog) *JobLogUpdateOne {
	jluo.mutation.Where(ps...)
	return jluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (jluo *JobLogUpdateOne) Select(field string, fields ...string) *JobLogUpdateOne {
	jluo.fields = append([]string{field}, fields...)
	return jluo
}

// Save executes the query and returns the updated JobLog entity.
func (jluo *JobLogUpdateOne) Save(ctx context.Context) (*JobLog, error) {
	return withHooks(ctx, jluo.sqlSave, jluo.mutation, jluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (jluo *JobLogUpdateOne) SaveX(ctx context.Context) *JobLog {
	node, err := jluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (jluo *JobLogUpdateOne) Exec(ctx context.Context) error {
	_, err := jluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jluo *JobLogUpdateOne) ExecX(ctx context.Context) {
	if err := jluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (jluo *JobLogUpdateOne) check() error {
	if v, ok := jluo.mutation.Level(); ok {
		if err := joblog.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "JobLog.level": %w`, err)}
		}
	}
	if v, ok := jluo.mutation.What(); ok {
		if err := joblog.WhatValidator(v); err != nil {
			return &ValidationError{Name: "what", err: fmt.Errorf(`ent: validator failed for field "JobLog.what": %w`, err)}
		}
	}
	if jluo.mutation.JobCleared() && len(jluo.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "JobLog.job"`)
	}
	return nil
}

func (jluo *JobLogUpdateOne) sqlSave(ctx context.Context) (_node *JobLog, err error) {
	if err := jluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(joblog.Table, joblog.Columns, sqlgraph.NewFieldSpec(joblog.FieldID, field.TypeInt))
	id, ok := jluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "JobLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := jluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, joblog.FieldID)
		for _, f := range fields {
			if !joblog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != joblog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := jluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := jluo.mutation.Level(); ok {
		_spec.SetField(joblog.FieldLevel, field.TypeEnum, value)
	}
	if value, ok := jluo.mutation.Time(); ok {
		_spec.SetField(joblog.FieldTime, field.TypeTime, value)
	}
	if value, ok := jluo.mutation.Path(); ok {
		_spec.SetField(joblog.FieldPath, field.TypeString, value)
	}
	if jluo.mutation.PathCleared() {
		_spec.ClearField(joblog.FieldPath, field.TypeString)
	}
	if value, ok := jluo.mutation.What(); ok {
		_spec.SetField(joblog.FieldWhat, field.TypeEnum, value)
	}
	if value, ok := jluo.mutation.Size(); ok {
		_spec.SetField(joblog.FieldSize, field.TypeInt64, value)
	}
	if value, ok := jluo.mutation.AddedSize(); ok {
		_spec.AddField(joblog.FieldSize, field.TypeInt64, value)
	}
	if jluo.mutation.SizeCleared() {
		_spec.ClearField(joblog.FieldSize, field.TypeInt64)
	}
	if jluo.mutation.JobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   joblog.JobTable,
			Columns: []string{joblog.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := jluo.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   joblog.JobTable,
			Columns: []string{joblog.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &JobLog{config: jluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, jluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{joblog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	jluo.mutation.done = true
	return _node, nil
}
