// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/xzzpig/rclone-sync/internal/core/ent/job"
	"github.com/xzzpig/rclone-sync/internal/core/ent/joblog"
)

// JobLog is the model entity for the JobLog schema.
type JobLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Level holds the value of the "level" field.
	Level joblog.Level `json:"level,omitempty"`
	// Time holds the value of the "time" field.
	Time time.Time `json:"time,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the JobLogQuery when eager-loading is set.
	Edges        JobLogEdges `json:"edges"`
	job_logs     *uuid.UUID
	selectValues sql.SelectValues
}

// JobLogEdges holds the relations/edges for other nodes in the graph.
type JobLogEdges struct {
	// Job holds the value of the job edge.
	Job *Job `json:"job,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// JobOrErr returns the Job value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e JobLogEdges) JobOrErr() (*Job, error) {
	if e.Job != nil {
		return e.Job, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: job.Label}
	}
	return nil, &NotLoadedError{edge: "job"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JobLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case joblog.FieldID:
			values[i] = new(sql.NullInt64)
		case joblog.FieldLevel, joblog.FieldPath, joblog.FieldMessage:
			values[i] = new(sql.NullString)
		case joblog.FieldTime:
			values[i] = new(sql.NullTime)
		case joblog.ForeignKeys[0]: // job_logs
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JobLog fields.
func (jl *JobLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case joblog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			jl.ID = int(value.Int64)
		case joblog.FieldLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				jl.Level = joblog.Level(value.String)
			}
		case joblog.FieldTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field time", values[i])
			} else if value.Valid {
				jl.Time = value.Time
			}
		case joblog.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				jl.Path = value.String
			}
		case joblog.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				jl.Message = value.String
			}
		case joblog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field job_logs", values[i])
			} else if value.Valid {
				jl.job_logs = new(uuid.UUID)
				*jl.job_logs = *value.S.(*uuid.UUID)
			}
		default:
			jl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the JobLog.
// This includes values selected through modifiers, order, etc.
func (jl *JobLog) Value(name string) (ent.Value, error) {
	return jl.selectValues.Get(name)
}

// QueryJob queries the "job" edge of the JobLog entity.
func (jl *JobLog) QueryJob() *JobQuery {
	return NewJobLogClient(jl.config).QueryJob(jl)
}

// Update returns a builder for updating this JobLog.
// Note that you need to call JobLog.Unwrap() before calling this method if this JobLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (jl *JobLog) Update() *JobLogUpdateOne {
	return NewJobLogClient(jl.config).UpdateOne(jl)
}

// Unwrap unwraps the JobLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (jl *JobLog) Unwrap() *JobLog {
	_tx, ok := jl.config.driver.(*txDriver)
	if !ok {
		panic("ent: JobLog is not a transactional entity")
	}
	jl.config.driver = _tx.drv
	return jl
}

// String implements the fmt.Stringer.
func (jl *JobLog) String() string {
	var builder strings.Builder
	builder.WriteString("JobLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", jl.ID))
	builder.WriteString("level=")
	builder.WriteString(fmt.Sprintf("%v", jl.Level))
	builder.WriteString(", ")
	builder.WriteString("time=")
	builder.WriteString(jl.Time.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(jl.Path)
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(jl.Message)
	builder.WriteByte(')')
	return builder.String()
}

// JobLogs is a parsable slice of JobLog.
type JobLogs []*JobLog
