// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/xzzpig/rclone-sync/internal/api/graphql/model"
	"github.com/xzzpig/rclone-sync/internal/core/ent/connection"
	"github.com/xzzpig/rclone-sync/internal/core/ent/task"
	"github.com/xzzpig/rclone-sync/internal/core/ent/taskhook"
)

// TaskHookCreate is the builder for creating a TaskHook entity.
type TaskHookCreate struct {
	config
	mutation *TaskHookMutation
	hooks    []Hook
}

// SetEnabled sets the "enabled" field.
func (_c *TaskHookCreate) SetEnabled(v bool) *TaskHookCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *TaskHookCreate) SetNillableEnabled(v *bool) *TaskHookCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *TaskHookCreate) SetPriority(v int) *TaskHookCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *TaskHookCreate) SetNillablePriority(v *int) *TaskHookCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetEvent sets the "event" field.
func (_c *TaskHookCreate) SetEvent(v model.HookEvent) *TaskHookCreate {
	_c.mutation.SetEvent(v)
	return _c
}

// SetType sets the "type" field.
func (_c *TaskHookCreate) SetType(v model.HookType) *TaskHookCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetOnError sets the "on_error" field.
func (_c *TaskHookCreate) SetOnError(v model.HookOnError) *TaskHookCreate {
	_c.mutation.SetOnError(v)
	return _c
}

// SetNillableOnError sets the "on_error" field if the given value is not nil.
func (_c *TaskHookCreate) SetNillableOnError(v *model.HookOnError) *TaskHookCreate {
	if v != nil {
		_c.SetOnError(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *TaskHookCreate) SetConfig(v *model.HookConfig) *TaskHookCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *TaskHookCreate) SetTaskID(v uuid.UUID) *TaskHookCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_c *TaskHookCreate) SetNillableTaskID(v *uuid.UUID) *TaskHookCreate {
	if v != nil {
		_c.SetTaskID(*v)
	}
	return _c
}

// SetConnectionID sets the "connection_id" field.
func (_c *TaskHookCreate) SetConnectionID(v uuid.UUID) *TaskHookCreate {
	_c.mutation.SetConnectionID(v)
	return _c
}

// SetNillableConnectionID sets the "connection_id" field if the given value is not nil.
func (_c *TaskHookCreate) SetNillableConnectionID(v *uuid.UUID) *TaskHookCreate {
	if v != nil {
		_c.SetConnectionID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TaskHookCreate) SetCreatedAt(v time.Time) *TaskHookCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TaskHookCreate) SetNillableCreatedAt(v *time.Time) *TaskHookCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TaskHookCreate) SetUpdatedAt(v time.Time) *TaskHookCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TaskHookCreate) SetNillableUpdatedAt(v *time.Time) *TaskHookCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TaskHookCreate) SetID(v uuid.UUID) *TaskHookCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TaskHookCreate) SetNillableID(v *uuid.UUID) *TaskHookCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *TaskHookCreate) SetTask(v *Task) *TaskHookCreate {
	return _c.SetTaskID(v.ID)
}

// SetConnection sets the "connection" edge to the Connection entity.
func (_c *TaskHookCreate) SetConnection(v *Connection) *TaskHookCreate {
	return _c.SetConnectionID(v.ID)
}

// Mutation returns the TaskHookMutation object of the builder.
func (_c *TaskHookCreate) Mutation() *TaskHookMutation {
	return _c.mutation
}

// Save creates the TaskHook in the database.
func (_c *TaskHookCreate) Save(ctx context.Context) (*TaskHook, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskHookCreate) SaveX(ctx context.Context) *TaskHook {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskHookCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskHookCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskHookCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := taskhook.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.OnError(); !ok {
		v := taskhook.DefaultOnError
		_c.mutation.SetOnError(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := taskhook.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := taskhook.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := taskhook.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskHookCreate) check() error {
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "TaskHook.enabled"`)}
	}
	if _, ok := _c.mutation.Event(); !ok {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required field "TaskHook.event"`)}
	}
	if v, ok := _c.mutation.Event(); ok {
		if err := taskhook.EventValidator(v); err != nil {
			return &ValidationError{Name: "event", err: fmt.Errorf(`ent: validator failed for field "TaskHook.event": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "TaskHook.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := taskhook.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TaskHook.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OnError(); !ok {
		return &ValidationError{Name: "on_error", err: errors.New(`ent: missing required field "TaskHook.on_error"`)}
	}
	if v, ok := _c.mutation.OnError(); ok {
		if err := taskhook.OnErrorValidator(v); err != nil {
			return &ValidationError{Name: "on_error", err: fmt.Errorf(`ent: validator failed for field "TaskHook.on_error": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "TaskHook.config"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TaskHook.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TaskHook.updated_at"`)}
	}
	return nil
}

func (_c *TaskHookCreate) sqlSave(ctx context.Context) (*TaskHook, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskHookCreate) createSpec() (*TaskHook, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskHook{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(taskhook.Table, sqlgraph.NewFieldSpec(taskhook.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(taskhook.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(taskhook.FieldPriority, field.TypeInt, value)
		_node.Priority = &value
	}
	if value, ok := _c.mutation.Event(); ok {
		_spec.SetField(taskhook.FieldEvent, field.TypeEnum, value)
		_node.Event = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(taskhook.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.OnError(); ok {
		_spec.SetField(taskhook.FieldOnError, field.TypeEnum, value)
		_node.OnError = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(taskhook.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(taskhook.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(taskhook.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhook.TaskTable,
			Columns: []string{taskhook.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhook.ConnectionTable,
			Columns: []string{taskhook.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(connection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConnectionID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskHookCreateBulk is the builder for creating many TaskHook entities in bulk.
type TaskHookCreateBulk struct {
	config
	err      error
	builders []*TaskHookCreate
}

// Save creates the TaskHook entities in the database.
func (_c *TaskHookCreateBulk) Save(ctx context.Context) ([]*TaskHook, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskHook, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskHookMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskHookCreateBulk) SaveX(ctx context.Context) []*TaskHook {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskHookCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskHookCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
