// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/xzzpig/rclone-sync/internal/core/ent/job"
	"github.com/xzzpig/rclone-sync/internal/core/ent/task"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	mutation *TaskMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (tc *TaskCreate) SetName(s string) *TaskCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetSourcePath sets the "source_path" field.
func (tc *TaskCreate) SetSourcePath(s string) *TaskCreate {
	tc.mutation.SetSourcePath(s)
	return tc
}

// SetRemoteName sets the "remote_name" field.
func (tc *TaskCreate) SetRemoteName(s string) *TaskCreate {
	tc.mutation.SetRemoteName(s)
	return tc
}

// SetRemotePath sets the "remote_path" field.
func (tc *TaskCreate) SetRemotePath(s string) *TaskCreate {
	tc.mutation.SetRemotePath(s)
	return tc
}

// SetDirection sets the "direction" field.
func (tc *TaskCreate) SetDirection(t task.Direction) *TaskCreate {
	tc.mutation.SetDirection(t)
	return tc
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (tc *TaskCreate) SetNillableDirection(t *task.Direction) *TaskCreate {
	if t != nil {
		tc.SetDirection(*t)
	}
	return tc
}

// SetSchedule sets the "schedule" field.
func (tc *TaskCreate) SetSchedule(s string) *TaskCreate {
	tc.mutation.SetSchedule(s)
	return tc
}

// SetNillableSchedule sets the "schedule" field if the given value is not nil.
func (tc *TaskCreate) SetNillableSchedule(s *string) *TaskCreate {
	if s != nil {
		tc.SetSchedule(*s)
	}
	return tc
}

// SetRealtime sets the "realtime" field.
func (tc *TaskCreate) SetRealtime(b bool) *TaskCreate {
	tc.mutation.SetRealtime(b)
	return tc
}

// SetNillableRealtime sets the "realtime" field if the given value is not nil.
func (tc *TaskCreate) SetNillableRealtime(b *bool) *TaskCreate {
	if b != nil {
		tc.SetRealtime(*b)
	}
	return tc
}

// SetOptions sets the "options" field.
func (tc *TaskCreate) SetOptions(m map[string]interface{}) *TaskCreate {
	tc.mutation.SetOptions(m)
	return tc
}

// SetCreatedAt sets the "created_at" field.
func (tc *TaskCreate) SetCreatedAt(t time.Time) *TaskCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TaskCreate) SetNillableCreatedAt(t *time.Time) *TaskCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *TaskCreate) SetUpdatedAt(t time.Time) *TaskCreate {
	tc.mutation.SetUpdatedAt(t)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *TaskCreate) SetNillableUpdatedAt(t *time.Time) *TaskCreate {
	if t != nil {
		tc.SetUpdatedAt(*t)
	}
	return tc
}

// SetID sets the "id" field.
func (tc *TaskCreate) SetID(u uuid.UUID) *TaskCreate {
	tc.mutation.SetID(u)
	return tc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tc *TaskCreate) SetNillableID(u *uuid.UUID) *TaskCreate {
	if u != nil {
		tc.SetID(*u)
	}
	return tc
}

// AddJobIDs adds the "jobs" edge to the Job entity by IDs.
func (tc *TaskCreate) AddJobIDs(ids ...uuid.UUID) *TaskCreate {
	tc.mutation.AddJobIDs(ids...)
	return tc
}

// AddJobs adds the "jobs" edges to the Job entity.
func (tc *TaskCreate) AddJobs(j ...*Job) *TaskCreate {
	ids := make([]uuid.UUID, len(j))
	for i := range j {
		ids[i] = j[i].ID
	}
	return tc.AddJobIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (tc *TaskCreate) Mutation() *TaskMutation {
	return tc.mutation
}

// Save creates the Task in the database.
func (tc *TaskCreate) Save(ctx context.Context) (*Task, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TaskCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TaskCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TaskCreate) defaults() {
	if _, ok := tc.mutation.Direction(); !ok {
		v := task.DefaultDirection
		tc.mutation.SetDirection(v)
	}
	if _, ok := tc.mutation.Realtime(); !ok {
		v := task.DefaultRealtime
		tc.mutation.SetRealtime(v)
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := task.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		v := task.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
	if _, ok := tc.mutation.ID(); !ok {
		v := task.DefaultID()
		tc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TaskCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Task.name"`)}
	}
	if v, ok := tc.mutation.Name(); ok {
		if err := task.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Task.name": %w`, err)}
		}
	}
	if _, ok := tc.mutation.SourcePath(); !ok {
		return &ValidationError{Name: "source_path", err: errors.New(`ent: missing required field "Task.source_path"`)}
	}
	if v, ok := tc.mutation.SourcePath(); ok {
		if err := task.SourcePathValidator(v); err != nil {
			return &ValidationError{Name: "source_path", err: fmt.Errorf(`ent: validator failed for field "Task.source_path": %w`, err)}
		}
	}
	if _, ok := tc.mutation.RemoteName(); !ok {
		return &ValidationError{Name: "remote_name", err: errors.New(`ent: missing required field "Task.remote_name"`)}
	}
	if v, ok := tc.mutation.RemoteName(); ok {
		if err := task.RemoteNameValidator(v); err != nil {
			return &ValidationError{Name: "remote_name", err: fmt.Errorf(`ent: validator failed for field "Task.remote_name": %w`, err)}
		}
	}
	if _, ok := tc.mutation.RemotePath(); !ok {
		return &ValidationError{Name: "remote_path", err: errors.New(`ent: missing required field "Task.remote_path"`)}
	}
	if v, ok := tc.mutation.RemotePath(); ok {
		if err := task.RemotePathValidator(v); err != nil {
			return &ValidationError{Name: "remote_path", err: fmt.Errorf(`ent: validator failed for field "Task.remote_path": %w`, err)}
		}
	}
	if _, ok := tc.mutation.Direction(); !ok {
		return &ValidationError{Name: "direction", err: errors.New(`ent: missing required field "Task.direction"`)}
	}
	if v, ok := tc.mutation.Direction(); ok {
		if err := task.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "Task.direction": %w`, err)}
		}
	}
	if _, ok := tc.mutation.Realtime(); !ok {
		return &ValidationError{Name: "realtime", err: errors.New(`ent: missing required field "Task.realtime"`)}
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Task.created_at"`)}
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Task.updated_at"`)}
	}
	return nil
}

func (tc *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TaskCreate) createSpec() (*Task, *sqlgraph.CreateSpec) {
	var (
		_node = &Task{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(task.Table, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(task.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.SourcePath(); ok {
		_spec.SetField(task.FieldSourcePath, field.TypeString, value)
		_node.SourcePath = value
	}
	if value, ok := tc.mutation.RemoteName(); ok {
		_spec.SetField(task.FieldRemoteName, field.TypeString, value)
		_node.RemoteName = value
	}
	if value, ok := tc.mutation.RemotePath(); ok {
		_spec.SetField(task.FieldRemotePath, field.TypeString, value)
		_node.RemotePath = value
	}
	if value, ok := tc.mutation.Direction(); ok {
		_spec.SetField(task.FieldDirection, field.TypeEnum, value)
		_node.Direction = value
	}
	if value, ok := tc.mutation.Schedule(); ok {
		_spec.SetField(task.FieldSchedule, field.TypeString, value)
		_node.Schedule = value
	}
	if value, ok := tc.mutation.Realtime(); ok {
		_spec.SetField(task.FieldRealtime, field.TypeBool, value)
		_node.Realtime = value
	}
	if value, ok := tc.mutation.Options(); ok {
		_spec.SetField(task.FieldOptions, field.TypeJSON, value)
		_node.Options = value
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := tc.mutation.JobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.JobsTable,
			Columns: []string{task.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskCreateBulk is the builder for creating many Task entities in bulk.
type TaskCreateBulk struct {
	config
	err      error
	builders []*TaskCreate
}

// Save creates the Task entities in the database.
func (tcb *TaskCreateBulk) Save(ctx context.Context) ([]*Task, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Task, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TaskCreateBulk) SaveX(ctx context.Context) []*Task {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TaskCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TaskCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
