// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/xzzpig/rclone-sync/internal/core/ent/job"
	"github.com/xzzpig/rclone-sync/internal/core/ent/predicate"
	"github.com/xzzpig/rclone-sync/internal/core/ent/task"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (tu *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetName sets the "name" field.
func (tu *TaskUpdate) SetName(s string) *TaskUpdate {
	tu.mutation.SetName(s)
	return tu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableName(s *string) *TaskUpdate {
	if s != nil {
		tu.SetName(*s)
	}
	return tu
}

// SetSourcePath sets the "source_path" field.
func (tu *TaskUpdate) SetSourcePath(s string) *TaskUpdate {
	tu.mutation.SetSourcePath(s)
	return tu
}

// SetNillableSourcePath sets the "source_path" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableSourcePath(s *string) *TaskUpdate {
	if s != nil {
		tu.SetSourcePath(*s)
	}
	return tu
}

// SetRemoteName sets the "remote_name" field.
func (tu *TaskUpdate) SetRemoteName(s string) *TaskUpdate {
	tu.mutation.SetRemoteName(s)
	return tu
}

// SetNillableRemoteName sets the "remote_name" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableRemoteName(s *string) *TaskUpdate {
	if s != nil {
		tu.SetRemoteName(*s)
	}
	return tu
}

// SetRemotePath sets the "remote_path" field.
func (tu *TaskUpdate) SetRemotePath(s string) *TaskUpdate {
	tu.mutation.SetRemotePath(s)
	return tu
}

// SetNillableRemotePath sets the "remote_path" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableRemotePath(s *string) *TaskUpdate {
	if s != nil {
		tu.SetRemotePath(*s)
	}
	return tu
}

// SetDirection sets the "direction" field.
func (tu *TaskUpdate) SetDirection(t task.Direction) *TaskUpdate {
	tu.mutation.SetDirection(t)
	return tu
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableDirection(t *task.Direction) *TaskUpdate {
	if t != nil {
		tu.SetDirection(*t)
	}
	return tu
}

// SetSchedule sets the "schedule" field.
func (tu *TaskUpdate) SetSchedule(s string) *TaskUpdate {
	tu.mutation.SetSchedule(s)
	return tu
}

// SetNillableSchedule sets the "schedule" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableSchedule(s *string) *TaskUpdate {
	if s != nil {
		tu.SetSchedule(*s)
	}
	return tu
}

// ClearSchedule clears the value of the "schedule" field.
func (tu *TaskUpdate) ClearSchedule() *TaskUpdate {
	tu.mutation.ClearSchedule()
	return tu
}

// SetRealtime sets the "realtime" field.
func (tu *TaskUpdate) SetRealtime(b bool) *TaskUpdate {
	tu.mutation.SetRealtime(b)
	return tu
}

// SetNillableRealtime sets the "realtime" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableRealtime(b *bool) *TaskUpdate {
	if b != nil {
		tu.SetRealtime(*b)
	}
	return tu
}

// SetOptions sets the "options" field.
func (tu *TaskUpdate) SetOptions(m map[string]interface{}) *TaskUpdate {
	tu.mutation.SetOptions(m)
	return tu
}

// ClearOptions clears the value of the "options" field.
func (tu *TaskUpdate) ClearOptions() *TaskUpdate {
	tu.mutation.ClearOptions()
	return tu
}

// SetCreatedAt sets the "created_at" field.
func (tu *TaskUpdate) SetCreatedAt(t time.Time) *TaskUpdate {
	tu.mutation.SetCreatedAt(t)
	return tu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableCreatedAt(t *time.Time) *TaskUpdate {
	if t != nil {
		tu.SetCreatedAt(*t)
	}
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TaskUpdate) SetUpdatedAt(t time.Time) *TaskUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// AddJobIDs adds the "jobs" edge to the Job entity by IDs.
func (tu *TaskUpdate) AddJobIDs(ids ...uuid.UUID) *TaskUpdate {
	tu.mutation.AddJobIDs(ids...)
	return tu
}

// AddJobs adds the "jobs" edges to the Job entity.
func (tu *TaskUpdate) AddJobs(j ...*Job) *TaskUpdate {
	ids := make([]uuid.UUID, len(j))
	for i := range j {
		ids[i] = j[i].ID
	}
	return tu.AddJobIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (tu *TaskUpdate) Mutation() *TaskMutation {
	return tu.mutation
}

// ClearJobs clears all "jobs" edges to the Job entity.
func (tu *TaskUpdate) ClearJobs() *TaskUpdate {
	tu.mutation.ClearJobs()
	return tu
}

// RemoveJobIDs removes the "jobs" edge to Job entities by IDs.
func (tu *TaskUpdate) RemoveJobIDs(ids ...uuid.UUID) *TaskUpdate {
	tu.mutation.RemoveJobIDs(ids...)
	return tu
}

// RemoveJobs removes "jobs" edges to Job entities.
func (tu *TaskUpdate) RemoveJobs(j ...*Job) *TaskUpdate {
	ids := make([]uuid.UUID, len(j))
	for i := range j {
		ids[i] = j[i].ID
	}
	return tu.RemoveJobIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TaskUpdate) Save(ctx context.Context) (int, error) {
	tu.defaults()
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TaskUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TaskUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *TaskUpdate) defaults() {
	if _, ok := tu.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		tu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TaskUpdate) check() error {
	if v, ok := tu.mutation.Name(); ok {
		if err := task.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Task.name": %w`, err)}
		}
	}
	if v, ok := tu.mutation.SourcePath(); ok {
		if err := task.SourcePathValidator(v); err != nil {
			return &ValidationError{Name: "source_path", err: fmt.Errorf(`ent: validator failed for field "Task.source_path": %w`, err)}
		}
	}
	if v, ok := tu.mutation.RemoteName(); ok {
		if err := task.RemoteNameValidator(v); err != nil {
			return &ValidationError{Name: "remote_name", err: fmt.Errorf(`ent: validator failed for field "Task.remote_name": %w`, err)}
		}
	}
	if v, ok := tu.mutation.RemotePath(); ok {
		if err := task.RemotePathValidator(v); err != nil {
			return &ValidationError{Name: "remote_path", err: fmt.Errorf(`ent: validator failed for field "Task.remote_path": %w`, err)}
		}
	}
	if v, ok := tu.mutation.Direction(); ok {
		if err := task.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "Task.direction": %w`, err)}
		}
	}
	return nil
}

func (tu *TaskUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Name(); ok {
		_spec.SetField(task.FieldName, field.TypeString, value)
	}
	if value, ok := tu.mutation.SourcePath(); ok {
		_spec.SetField(task.FieldSourcePath, field.TypeString, value)
	}
	if value, ok := tu.mutation.RemoteName(); ok {
		_spec.SetField(task.FieldRemoteName, field.TypeString, value)
	}
	if value, ok := tu.mutation.RemotePath(); ok {
		_spec.SetField(task.FieldRemotePath, field.TypeString, value)
	}
	if value, ok := tu.mutation.Direction(); ok {
		_spec.SetField(task.FieldDirection, field.TypeEnum, value)
	}
	if value, ok := tu.mutation.Schedule(); ok {
		_spec.SetField(task.FieldSchedule, field.TypeString, value)
	}
	if tu.mutation.ScheduleCleared() {
		_spec.ClearField(task.FieldSchedule, field.TypeString)
	}
	if value, ok := tu.mutation.Realtime(); ok {
		_spec.SetField(task.FieldRealtime, field.TypeBool, value)
	}
	if value, ok := tu.mutation.Options(); ok {
		_spec.SetField(task.FieldOptions, field.TypeJSON, value)
	}
	if tu.mutation.OptionsCleared() {
		_spec.ClearField(task.FieldOptions, field.TypeJSON)
	}
	if value, ok := tu.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if tu.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.JobsTable,
			Columns: []string{task.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedJobsIDs(); len(nodes) > 0 && !tu.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.JobsTable,
			Columns: []string{task.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.JobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.JobsTable,
			Columns: []string{task.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetName sets the "name" field.
func (tuo *TaskUpdateOne) SetName(s string) *TaskUpdateOne {
	tuo.mutation.SetName(s)
	return tuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableName(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetName(*s)
	}
	return tuo
}

// SetSourcePath sets the "source_path" field.
func (tuo *TaskUpdateOne) SetSourcePath(s string) *TaskUpdateOne {
	tuo.mutation.SetSourcePath(s)
	return tuo
}

// SetNillableSourcePath sets the "source_path" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableSourcePath(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetSourcePath(*s)
	}
	return tuo
}

// SetRemoteName sets the "remote_name" field.
func (tuo *TaskUpdateOne) SetRemoteName(s string) *TaskUpdateOne {
	tuo.mutation.SetRemoteName(s)
	return tuo
}

// SetNillableRemoteName sets the "remote_name" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableRemoteName(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetRemoteName(*s)
	}
	return tuo
}

// SetRemotePath sets the "remote_path" field.
func (tuo *TaskUpdateOne) SetRemotePath(s string) *TaskUpdateOne {
	tuo.mutation.SetRemotePath(s)
	return tuo
}

// SetNillableRemotePath sets the "remote_path" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableRemotePath(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetRemotePath(*s)
	}
	return tuo
}

// SetDirection sets the "direction" field.
func (tuo *TaskUpdateOne) SetDirection(t task.Direction) *TaskUpdateOne {
	tuo.mutation.SetDirection(t)
	return tuo
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableDirection(t *task.Direction) *TaskUpdateOne {
	if t != nil {
		tuo.SetDirection(*t)
	}
	return tuo
}

// SetSchedule sets the "schedule" field.
func (tuo *TaskUpdateOne) SetSchedule(s string) *TaskUpdateOne {
	tuo.mutation.SetSchedule(s)
	return tuo
}

// SetNillableSchedule sets the "schedule" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableSchedule(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetSchedule(*s)
	}
	return tuo
}

// ClearSchedule clears the value of the "schedule" field.
func (tuo *TaskUpdateOne) ClearSchedule() *TaskUpdateOne {
	tuo.mutation.ClearSchedule()
	return tuo
}

// SetRealtime sets the "realtime" field.
func (tuo *TaskUpdateOne) SetRealtime(b bool) *TaskUpdateOne {
	tuo.mutation.SetRealtime(b)
	return tuo
}

// SetNillableRealtime sets the "realtime" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableRealtime(b *bool) *TaskUpdateOne {
	if b != nil {
		tuo.SetRealtime(*b)
	}
	return tuo
}

// SetOptions sets the "options" field.
func (tuo *TaskUpdateOne) SetOptions(m map[string]interface{}) *TaskUpdateOne {
	tuo.mutation.SetOptions(m)
	return tuo
}

// ClearOptions clears the value of the "options" field.
func (tuo *TaskUpdateOne) ClearOptions() *TaskUpdateOne {
	tuo.mutation.ClearOptions()
	return tuo
}

// SetCreatedAt sets the "created_at" field.
func (tuo *TaskUpdateOne) SetCreatedAt(t time.Time) *TaskUpdateOne {
	tuo.mutation.SetCreatedAt(t)
	return tuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableCreatedAt(t *time.Time) *TaskUpdateOne {
	if t != nil {
		tuo.SetCreatedAt(*t)
	}
	return tuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TaskUpdateOne) SetUpdatedAt(t time.Time) *TaskUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// AddJobIDs adds the "jobs" edge to the Job entity by IDs.
func (tuo *TaskUpdateOne) AddJobIDs(ids ...uuid.UUID) *TaskUpdateOne {
	tuo.mutation.AddJobIDs(ids...)
	return tuo
}

// AddJobs adds the "jobs" edges to the Job entity.
func (tuo *TaskUpdateOne) AddJobs(j ...*Job) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(j))
	for i := range j {
		ids[i] = j[i].ID
	}
	return tuo.AddJobIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (tuo *TaskUpdateOne) Mutation() *TaskMutation {
	return tuo.mutation
}

// ClearJobs clears all "jobs" edges to the Job entity.
func (tuo *TaskUpdateOne) ClearJobs() *TaskUpdateOne {
	tuo.mutation.ClearJobs()
	return tuo
}

// RemoveJobIDs removes the "jobs" edge to Job entities by IDs.
func (tuo *TaskUpdateOne) RemoveJobIDs(ids ...uuid.UUID) *TaskUpdateOne {
	tuo.mutation.RemoveJobIDs(ids...)
	return tuo
}

// RemoveJobs removes "jobs" edges to Job entities.
func (tuo *TaskUpdateOne) RemoveJobs(j ...*Job) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(j))
	for i := range j {
		ids[i] = j[i].ID
	}
	return tuo.RemoveJobIDs(ids...)
}

// Where appends a list predicates to the TaskUpdate builder.
func (tuo *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Task entity.
func (tuo *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	tuo.defaults()
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *TaskUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		tuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TaskUpdateOne) check() error {
	if v, ok := tuo.mutation.Name(); ok {
		if err := task.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Task.name": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.SourcePath(); ok {
		if err := task.SourcePathValidator(v); err != nil {
			return &ValidationError{Name: "source_path", err: fmt.Errorf(`ent: validator failed for field "Task.source_path": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.RemoteName(); ok {
		if err := task.RemoteNameValidator(v); err != nil {
			return &ValidationError{Name: "remote_name", err: fmt.Errorf(`ent: validator failed for field "Task.remote_name": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.RemotePath(); ok {
		if err := task.RemotePathValidator(v); err != nil {
			return &ValidationError{Name: "remote_path", err: fmt.Errorf(`ent: validator failed for field "Task.remote_path": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.Direction(); ok {
		if err := task.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "Task.direction": %w`, err)}
		}
	}
	return nil
}

func (tuo *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Name(); ok {
		_spec.SetField(task.FieldName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.SourcePath(); ok {
		_spec.SetField(task.FieldSourcePath, field.TypeString, value)
	}
	if value, ok := tuo.mutation.RemoteName(); ok {
		_spec.SetField(task.FieldRemoteName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.RemotePath(); ok {
		_spec.SetField(task.FieldRemotePath, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Direction(); ok {
		_spec.SetField(task.FieldDirection, field.TypeEnum, value)
	}
	if value, ok := tuo.mutation.Schedule(); ok {
		_spec.SetField(task.FieldSchedule, field.TypeString, value)
	}
	if tuo.mutation.ScheduleCleared() {
		_spec.ClearField(task.FieldSchedule, field.TypeString)
	}
	if value, ok := tuo.mutation.Realtime(); ok {
		_spec.SetField(task.FieldRealtime, field.TypeBool, value)
	}
	if value, ok := tuo.mutation.Options(); ok {
		_spec.SetField(task.FieldOptions, field.TypeJSON, value)
	}
	if tuo.mutation.OptionsCleared() {
		_spec.ClearField(task.FieldOptions, field.TypeJSON)
	}
	if value, ok := tuo.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if tuo.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.JobsTable,
			Columns: []string{task.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedJobsIDs(); len(nodes) > 0 && !tuo.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.JobsTable,
			Columns: []string{task.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.JobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.JobsTable,
			Columns: []string{task.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Task{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
