// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/xzzpig/rclone-sync/internal/api/graphql/model"
	"github.com/xzzpig/rclone-sync/internal/core/ent/connection"
	"github.com/xzzpig/rclone-sync/internal/core/ent/task"
	"github.com/xzzpig/rclone-sync/internal/core/ent/taskhook"
)

// TaskHook is the model entity for the TaskHook schema.
type TaskHook struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority *int `json:"priority,omitempty"`
	// Event holds the value of the "event" field.
	Event model.HookEvent `json:"event,omitempty"`
	// Type holds the value of the "type" field.
	Type model.HookType `json:"type,omitempty"`
	// OnError holds the value of the "on_error" field.
	OnError model.HookOnError `json:"on_error,omitempty"`
	// Config holds the value of the "config" field.
	Config *model.HookConfig `json:"config,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID *uuid.UUID `json:"task_id,omitempty"`
	// ConnectionID holds the value of the "connection_id" field.
	ConnectionID *uuid.UUID `json:"connection_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskHookQuery when eager-loading is set.
	Edges        TaskHookEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TaskHookEdges holds the relations/edges for other nodes in the graph.
type TaskHookEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// Connection holds the value of the connection edge.
	Connection *Connection `json:"connection,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskHookEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// ConnectionOrErr returns the Connection value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskHookEdges) ConnectionOrErr() (*Connection, error) {
	if e.Connection != nil {
		return e.Connection, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: connection.Label}
	}
	return nil, &NotLoadedError{edge: "connection"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskHook) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case taskhook.FieldTaskID, taskhook.FieldConnectionID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case taskhook.FieldConfig:
			values[i] = new([]byte)
		case taskhook.FieldEnabled:
			values[i] = new(sql.NullBool)
		case taskhook.FieldPriority:
			values[i] = new(sql.NullInt64)
		case taskhook.FieldEvent, taskhook.FieldType, taskhook.FieldOnError:
			values[i] = new(sql.NullString)
		case taskhook.FieldCreatedAt, taskhook.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case taskhook.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskHook fields.
func (_m *TaskHook) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case taskhook.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case taskhook.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case taskhook.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = new(int)
				*_m.Priority = int(value.Int64)
			}
		case taskhook.FieldEvent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event", values[i])
			} else if value.Valid {
				_m.Event = model.HookEvent(value.String)
			}
		case taskhook.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = model.HookType(value.String)
			}
		case taskhook.FieldOnError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field on_error", values[i])
			} else if value.Valid {
				_m.OnError = model.HookOnError(value.String)
			}
		case taskhook.FieldConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Config); err != nil {
					return fmt.Errorf("unmarshal field config: %w", err)
				}
			}
		case taskhook.FieldTaskID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = new(uuid.UUID)
				*_m.TaskID = *value.S.(*uuid.UUID)
			}
		case taskhook.FieldConnectionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field connection_id", values[i])
			} else if value.Valid {
				_m.ConnectionID = new(uuid.UUID)
				*_m.ConnectionID = *value.S.(*uuid.UUID)
			}
		case taskhook.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case taskhook.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TaskHook.
// This includes values selected through modifiers, order, etc.
func (_m *TaskHook) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the TaskHook entity.
func (_m *TaskHook) QueryTask() *TaskQuery {
	return NewTaskHookClient(_m.config).QueryTask(_m)
}

// QueryConnection queries the "connection" edge of the TaskHook entity.
func (_m *TaskHook) QueryConnection() *ConnectionQuery {
	return NewTaskHookClient(_m.config).QueryConnection(_m)
}

// Update returns a builder for updating this TaskHook.
// Note that you need to call TaskHook.Unwrap() before calling this method if this TaskHook
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TaskHook) Update() *TaskHookUpdateOne {
	return NewTaskHookClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TaskHook entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TaskHook) Unwrap() *TaskHook {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskHook is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TaskHook) String() string {
	var builder strings.Builder
	builder.WriteString("TaskHook(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	if v := _m.Priority; v != nil {
		builder.WriteString("priority=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("event=")
	builder.WriteString(fmt.Sprintf("%v", _m.Event))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("on_error=")
	builder.WriteString(fmt.Sprintf("%v", _m.OnError))
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(fmt.Sprintf("%v", _m.Config))
	builder.WriteString(", ")
	if v := _m.TaskID; v != nil {
		builder.WriteString("task_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ConnectionID; v != nil {
		builder.WriteString("connection_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TaskHooks is a parsable slice of TaskHook.
type TaskHooks []*TaskHook
