// Code generated by ent, DO NOT EDIT.

package task

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the task type in the database.
	Label = "task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSourcePath holds the string denoting the source_path field in the database.
	FieldSourcePath = "source_path"
	// FieldRemoteName holds the string denoting the remote_name field in the database.
	FieldRemoteName = "remote_name"
	// FieldRemotePath holds the string denoting the remote_path field in the database.
	FieldRemotePath = "remote_path"
	// FieldDirection holds the string denoting the direction field in the database.
	FieldDirection = "direction"
	// FieldSchedule holds the string denoting the schedule field in the database.
	FieldSchedule = "schedule"
	// FieldRealtime holds the string denoting the realtime field in the database.
	FieldRealtime = "realtime"
	// FieldOptions holds the string denoting the options field in the database.
	FieldOptions = "options"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeJobs holds the string denoting the jobs edge name in mutations.
	EdgeJobs = "jobs"
	// Table holds the table name of the task in the database.
	Table = "tasks"
	// JobsTable is the table that holds the jobs relation/edge.
	JobsTable = "jobs"
	// JobsInverseTable is the table name for the Job entity.
	// It exists in this package in order to avoid circular dependency with the "job" package.
	JobsInverseTable = "jobs"
	// JobsColumn is the table column denoting the jobs relation/edge.
	JobsColumn = "task_jobs"
)

// Columns holds all SQL columns for task fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSourcePath,
	FieldRemoteName,
	FieldRemotePath,
	FieldDirection,
	FieldSchedule,
	FieldRealtime,
	FieldOptions,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SourcePathValidator is a validator for the "source_path" field. It is called by the builders before save.
	SourcePathValidator func(string) error
	// RemoteNameValidator is a validator for the "remote_name" field. It is called by the builders before save.
	RemoteNameValidator func(string) error
	// RemotePathValidator is a validator for the "remote_path" field. It is called by the builders before save.
	RemotePathValidator func(string) error
	// DefaultRealtime holds the default value on creation for the "realtime" field.
	DefaultRealtime bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Direction defines the type for the "direction" enum field.
type Direction string

// DirectionBidirectional is the default value of the Direction enum.
const DefaultDirection = DirectionBidirectional

// Direction values.
const (
	DirectionUpload        Direction = "upload"
	DirectionDownload      Direction = "download"
	DirectionBidirectional Direction = "bidirectional"
)

func (d Direction) String() string {
	return string(d)
}

// DirectionValidator is a validator for the "direction" field enum values. It is called by the builders before save.
func DirectionValidator(d Direction) error {
	switch d {
	case DirectionUpload, DirectionDownload, DirectionBidirectional:
		return nil
	default:
		return fmt.Errorf("task: invalid enum value for direction field: %q", d)
	}
}

// OrderOption defines the ordering options for the Task queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySourcePath orders the results by the source_path field.
func BySourcePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourcePath, opts...).ToFunc()
}

// ByRemoteName orders the results by the remote_name field.
func ByRemoteName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteName, opts...).ToFunc()
}

// ByRemotePath orders the results by the remote_path field.
func ByRemotePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemotePath, opts...).ToFunc()
}

// ByDirection orders the results by the direction field.
func ByDirection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirection, opts...).ToFunc()
}

// BySchedule orders the results by the schedule field.
func BySchedule(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSchedule, opts...).ToFunc()
}

// ByRealtime orders the results by the realtime field.
func ByRealtime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealtime, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByJobsCount orders the results by jobs count.
func ByJobsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newJobsStep(), opts...)
	}
}

// ByJobs orders the results by jobs terms.
func ByJobs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJobsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newJobsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JobsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, JobsTable, JobsColumn),
	)
}
