// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ConnectionsColumns holds the columns for the "connections" table.
	ConnectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeString},
		{Name: "encrypted_config", Type: field.TypeBytes},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ConnectionsTable holds the schema information for the "connections" table.
	ConnectionsTable = &schema.Table{
		Name:       "connections",
		Columns:    ConnectionsColumns,
		PrimaryKey: []*schema.Column{ConnectionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "connection_name",
				Unique:  true,
				Columns: []*schema.Column{ConnectionsColumns[1]},
			},
			{
				Name:    "connection_type",
				Unique:  false,
				Columns: []*schema.Column{ConnectionsColumns[2]},
			},
		},
	}
	// JobsColumns holds the columns for the "jobs" table.
	JobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "running", "success", "failed", "cancelled"}, Default: "pending"},
		{Name: "trigger", Type: field.TypeEnum, Enums: []string{"manual", "schedule", "realtime"}},
		{Name: "start_time", Type: field.TypeTime},
		{Name: "end_time", Type: field.TypeTime, Nullable: true},
		{Name: "files_transferred", Type: field.TypeInt, Default: 0},
		{Name: "bytes_transferred", Type: field.TypeInt64, Default: 0},
		{Name: "errors", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "task_jobs", Type: field.TypeUUID},
	}
	// JobsTable holds the schema information for the "jobs" table.
	JobsTable = &schema.Table{
		Name:       "jobs",
		Columns:    JobsColumns,
		PrimaryKey: []*schema.Column{JobsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "jobs_tasks_jobs",
				Columns:    []*schema.Column{JobsColumns[8]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// JobLogsColumns holds the columns for the "job_logs" table.
	JobLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "level", Type: field.TypeEnum, Enums: []string{"info", "warning", "error"}},
		{Name: "time", Type: field.TypeTime},
		{Name: "path", Type: field.TypeString, Nullable: true},
		{Name: "what", Type: field.TypeEnum, Enums: []string{"upload", "download", "delete", "move", "error", "unknown"}, Default: "unknown"},
		{Name: "size", Type: field.TypeInt64, Nullable: true},
		{Name: "job_logs", Type: field.TypeUUID},
	}
	// JobLogsTable holds the schema information for the "job_logs" table.
	JobLogsTable = &schema.Table{
		Name:       "job_logs",
		Columns:    JobLogsColumns,
		PrimaryKey: []*schema.Column{JobLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "job_logs_jobs_logs",
				Columns:    []*schema.Column{JobLogsColumns[6]},
				RefColumns: []*schema.Column{JobsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "source_path", Type: field.TypeString},
		{Name: "remote_path", Type: field.TypeString},
		{Name: "direction", Type: field.TypeEnum, Enums: []string{"upload", "download", "bidirectional"}, Default: "bidirectional"},
		{Name: "schedule", Type: field.TypeString, Nullable: true},
		{Name: "realtime", Type: field.TypeBool, Default: false},
		{Name: "options", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "connection_id", Type: field.TypeUUID, Nullable: true},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tasks_connections_tasks",
				Columns:    []*schema.Column{TasksColumns[10]},
				RefColumns: []*schema.Column{ConnectionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ConnectionsTable,
		JobsTable,
		JobLogsTable,
		TasksTable,
	}
)

func init() {
	JobsTable.ForeignKeys[0].RefTable = TasksTable
	JobLogsTable.ForeignKeys[0].RefTable = JobsTable
	TasksTable.ForeignKeys[0].RefTable = ConnectionsTable
}
